## 1. 합성소견서 로드

In [3]:
import pandas as pd

# Set pandas display options
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.width', 100)        # Set the display width to 1000 characters
pd.set_option('display.max_colwidth', None) # Allow the full content of each column to be displayed

In [4]:
df_final_audit = pd.read_csv('./comprehensive_audit_final.csv')

In [6]:
df_final_audit

,개인아이디,합성_소견서,원본_최종 수축기 혈압,추출_최종 수축기 혈압,원본_최종 이완기 혈압,추출_최종 이완기 혈압,원본_체질량지수,추출_체질량지수,원본_허리둘레,추출_허리둘레,원본_공복혈당,추출_공복혈당,원본_당화혈색소,추출_당화혈색소,원본_총콜레스테롤,추출_총콜레스테롤,원본_HDL-콜레스테롤,추출_HDL-콜레스테롤,원본_중성지방,추출_중성지방,원본_LDL-콜레스테롤(직접검사),추출_LDL-콜레스테롤(직접검사),원본_비만 유병여부,추출_비만 유병여부,원본_1년간 체중 변화 여부,추출_1년간 체중 변화 여부,원본_1년간 음주빈도,추출_1년간 음주빈도,원본_한번에 마시는 음주량,추출_한번에 마시는 음주량,원본_현재 일반담배 흡연 여부,추출_현재 일반담배 흡연 여부,원본_유산소 신체활동 실천율,추출_유산소 신체활동 실천율,원본_아침식사 빈도,추출_아침식사 빈도,원본_평소 스트레스 인지 정도,추출_평소 스트레스 인지 정도,원본_혈압조절제 복용 여부,추출_혈압조절제 복용 여부,원본_당뇨병약 복용 여부,추출_당뇨병약 복용 여부,원본_이상지질혈증 약복용 여부,추출_이상지질혈증 약복용 여부,원본_당뇨병 유병여부,추출_당뇨병 유병여부,원본_고혈압 유병여부,추출_고혈압 유병여부,원본_고콜레스테롤혈증 유병여부,추출_고콜레스테롤혈증 유병여부
0,A801223802,"### 건강검진 소견서\n\n#### 1. 신체계측 및 혈압\n수축기 혈압 133 mmHg, 이완기 혈압 76 mmHg로 경계치입니다. 체질량지수는 26.9 kg/m²로 1단계 비만이며, 허리둘레 88.8 cm로 복부비만 기준을 초과하고 있습니다.\n\n#### 2. 대사 지표\n공복혈당 102 mg/dL, 당화혈색소 5.8%로 경계치입니다. 총콜레스테롤 230 mg/dL, HDL-콜레스테롤 43 mg/dL, LDL-콜레스테롤 146 mg/dL, 중성지방 274 mg/dL로 중성지방이 높습니다.\n\n#### 3. 생활습관 및 건강행태\n1년간 체중 증가가 관찰되었습니다. 음주는 월 2~4회, 한번에 7~9잔 정도입니다. 현재는 담배를 피우지 않고 있지만 과거에는 흡연하였었습니다. 유산소 운동을 실천하지 않고 있으며, 아침식사는 주 1~2회로 적습니다. 스트레스는 조금 느끼는 편입니다.\n\n#### 4. 약물 복용 및 질환 유병 현황\n혈압약, 당뇨약, 이상지질혈증약 모두 복용하지 않습니다. 당뇨병, 고혈압 유병 여부는 확인되지 않았지만, 고콜레스테롤혈증은 정상입니다.\n\n#### 5. 종합 의견\n전반적으로 일부 경계치 수치와 생활습관 개선이 필요합니다. 체중 감소와 유산소 운동 실천, 규칙적인 식사 습관을 유지하시고, 연 1회 정기검진을 권장합니다.\n\n---\n\n[CLINICAL_DATA_RECORD]\n- 최종 수축기 혈압: 133.0 mmHg\n- 최종 이완기 혈압: 76.0 mmHg\n- 체질량지수: 26.91984854426037 kg/m²\n- 허리둘레: 88.8 cm\n- 공복혈당: 102.0 mg/dL\n- 당화혈색소: 5.8%\n- 총콜레스테롤: 230.0 mg/dL\n- HDL-콜레스테롤: 43.0 mg/dL\n- 중성지방: 274.0 mg/dL\n- LDL-콜레스테롤(직접검사): 146.0 mg/dL\n- 비만 유병여부: 1단계비만\n- 1년간 체중 변화 여부: 체중 증가\n- 1년간 음주빈도: 월 2~4회\n- 한번에 마시는 음주량: 7~9잔\n- 현재 일반담배 흡연 여부: 과거에는 피웠으나 현재 안 피움\n- 유산소 신체활동 실천율: 미실천\n- 아침식사 빈도: 주 1~2회\n- 평소 스트레스 인지 정도: 조금 느끼는 편임\n- 혈압조절제 복용 여부: 비해당\n- 당뇨병약 복용 여부: 비해당\n- 이상지질혈증 약복용 여부: 비해당\n- 당뇨병 유병여부: 결측치\n- 고혈압 유병여부: 결측치\n- 고콜레스테롤혈증 유병여부: 정상",133.0,133.0 mmHg,76.0,76.0 mmHg,26.919849,26.91984854426037 kg/m²,88.8,88.8 cm,102.0,102.0 mg/dL,5.8,5.8%,230.0,230.0 mg/dL,43.0,43.0 mg/dL,274.0,274.0 mg/dL,146.0,146.0 mg/dL,1단계비만,1단계비만,체중 증가,체중 증가,월 2~4회,월 2~4회,7~9잔,7~9잔,과거에는 피웠으나 현재 안 피움,과거에는 피웠으나 현재 안 피움,미실천,미실천,주 1~2회,주 1~2회,조금 느끼는 편임,조금 느끼는 편임,비해당,비해당,비해당,비해당,비해당,비해당,결측치,결측치,결측치,결측치,정상,정상
1,A801230601,"### 건강검진 소견서\n\n#### 1. 신체계측 및 혈압\n수축기 혈압 137 mmHg, 이완기 혈압 85 mmHg로 고혈압 경계치입니다. 체질량지수는 25.1 kg/m²로 1단계 비만이며, 허리둘레 85.3 cm로 복부비만 기준을 초과하고 있습니다.\n\n#### 2. 대사 지표\n공복혈당 96 mg/dL, 당화혈색소 5.9%로 경계값입니다. 총콜레스테롤 205 mg/dL, HDL-콜레스테롤 43 mg/dL, LDL-콜레스테롤 97 mg/dL, 중성지방 266 mg/dL로 중성지방이 높습니다.\n\n#### 3. 생활습관 및 건강행태\n1단계 비만으로, 최근 1년간 체중 변화는 없습니다. 음주는 주 2~3회 정도이며, 한번에 7~9잔을 섭취합니다. 과거에는 담배를 피웠으나 현재는 흡연하지 않고 있습니다. 유산소 운동을 실천하고 있으며, 아침식사는 주 5~7회 규칙적으로 섭취하고 있습니다. 스트레스는 조금 느끼는 편입니다.\n\n#### 4. 약물 복용 및 질환 유병 현황\n혈압조절제를 매일 복용하고 있으며, 당뇨병약과 이상지질혈증약은 복용하지 않습니다. 당뇨병, 고혈압 유병 여부는 확인되지 않았지만, 고콜레스테롤혈증은 정상입니다.\n\n#### 5. 종합 의견\n혈압과 중성지방이 높은 경계치입니다. 현재의 운동 습관과 식습관을 유지하시되, 음주량을 줄이고 체중 관리를 위해 적극적인 운동을 실천하시길 권장합니다. 연 1회 정기검진을 통해 건강 상태를 모니터링하시기 바랍니다.\n\n---\n\n**[CLINICAL_DATA_RECORD]**\n\n- 최종 수축기 혈압: 137.0 mmHg\n- 최종 이완기 혈압: 85.0 mmHg\n- 체질량지수: 25.081022062367428 kg/m²\n- 허리둘레: 85.3 cm\n- 공복혈당: 96.0 mg/dL\n- 당화혈색소: 5.9%\n- 총콜레스테롤: 205.0 mg/dL\n- HDL-콜레스테롤: 43.0 mg/dL\n- 중성지방: 266.0 mg/dL\n- LDL-콜레스테롤(직접검사): 97.0 mg/dL\n- 비만 유병여부: 1단계비만\n- 1년간 체중 변화 여부: 변화 없음\n- 1년간 음주빈도: 주 2~3회 정도\n- 한 번에 마시는 음주량: 7~9잔\n- 현재 일반담배 흡연 여부: 과거에는 피웠으나 현재 안 피움\n- 유산소 신체활동 실천율: 실천\n- 아침식사 빈도: 주 5~7회\n- 평소 스트레스 인지 정도: 조금 느끼는 편임\n- 혈압조절제 복용 여부: 매일 복용함\n- 당뇨병약 복용 여부: 비해당\n- 이상지질혈증 약복용 여부: 비해당\n- 당뇨병 유병여부: 결측치\n- 고혈압 유병여부: 결측치\n- 고콜레스테롤혈증 유병여부: 정상",137.0,137.0 mmHg,85.0,85.0 mmHg,25.081022,25.081022062367428 kg/m²,85.3,85.3 cm,96.0,96.0 mg/dL,5.9,5.9%,205.0,205.0 mg/dL,43.0,43.0 mg/dL,266.0,266.0 mg/dL,97.0,97.0 mg/dL,1단계비만,1단계비만,변화 없음,변화 없음,주 2~3회 정도,주 2~3회 정도,7~9잔,7~9잔,과거에는 피웠으나 현재 안 피움,과거에는 피웠으나 현재 안 피움,실천,실천,주 5~7회,주 5~7회,조금 느끼는 편임,조금 느끼는 편임,매일 복용함,매일 복용함,비해당,비해당,비해당,비해당,결측치,결측치,결측치,결측치,정상,정상
2,A801245901,"### 건강검진 소견서\n\n#### 1. 신체계측 및 혈압\n수축기 혈압 148 mmHg, 이완기 혈압 102 mmHg로 고혈압 범위입니다. 체질량지수는 27.0 kg/m²로 1단계 비만이며, 허리둘레 91.3 cm로 복부비만 기준 초과입니다.\n\n#### 2. 대사 지표\n공복혈당 89 mg/dL, 당화혈색소 6.0%로 정상입니다. 총콜레스테롤 203 mg/dL, HDL-콜레스테롤 40 mg/dL, LDL-콜레스테롤 95 mg/dL, 중성지방 289 mg/dL로 중성지방이 상승되어 있습니다.\n\n#### 3. 생활습관 및 건강행태\n비만 유병 1단계 비만입니다. 최근 1년간 체중 변화 없으며, 음주는 월 1회 정도입니다. 현재는 일반 담배를 피우지 않고 있으며, 유산소 운동을 주 3회 이상 실천 중입니다. 아침식사는 주 5~7회 규칙적으로 하며, 스트레스는 거의 느끼지 않는 편입니다.\n\n#### 4. 약물 복용 및 질환 유병 현황\n혈압조절제를 매일 복용하고 있으며, 당뇨병약은 복용하지 않습니다. 이상지질혈증 약도 매일 복용 중입니다. 당뇨병 유병 여부는 확인되지 않았지만, 고혈압과 고콜레스테롤혈증은 확인되었습니다.\n\n#### 5. 종합 의견\n고혈압과 1단계 비만, 중성지방 상승 등의 문제점이 있으나, 현재의 규칙적인 운동 습관과 식습관을 유지하시고, 연 1회 정기검진을 통해 건강 상태를 모니터링하시길 권장합니다.\n\n---\n\n#### [CLINICAL_DATA_RECORD]\n- 최종 수축기 혈압: 148.0 mmHg\n- 최종 이완기 혈압: 102.0 mmHg\n- 체질량지수: 26.988636363636363 kg/m²\n- 허리둘레: 91.3 cm\n- 공복혈당: 89.0 mg/dL\n- 당화혈색소: 6.0%\n- 총콜레스테롤: 203.0 mg/dL\n- HDL-콜레스테롤: 40.0 mg/dL\n- 중성지방: 289.0 mg/dL\n- LDL-콜레스테롤(직접검사): 95.0 mg/dL\n- 비만 유병여부: 1단계비만\n- 1년간 체중 변화 여부: 변화 없음\n- 1년간 음주빈도: 월 1회 정도\n- 한번에 마시는 음주량: 5~6잔\n- 현재 일반담배 흡연 여부: 과거에는 피웠으나 현재 안 피움\n- 유산소 신체활동 실천율: 실천\n- 아침식사 빈도: 주 5~7회\n- 평소 스트레스 인지 정도: 거의 느끼지 않음\n- 혈압조절제 복용 여부: 매일 복용함\n- 당뇨병약 복용 여부: 비해당\n- 이상지질혈증 약복용 여부: 매일 복용함\n- 당뇨병 유병여부: 결측치\n- 고혈압 유병여부: 결측치\n- 고콜레스테롤혈증 유병여부: 고콜레스테롤혈증",148.0,148.0 mmHg,102.0,102.0 mmHg,26.988636,26.988636363636363 kg/m²,91.3,91.3 cm,89.0,89.0 mg/dL,6.0,6.0%,203.0,203.0 mg/dL,40.0,40.0 mg/dL,289.0,289.0 mg/dL,95.0,95.0 mg/dL,1단계비만,1단계비만,변화 없음,변화 없음,월 1회 정도,월 1회 정도,5~6잔,5~6잔,과거에는 피웠으나 현재 안 피움,과거에는 피웠으나 현재 안 피움,실천,실천,주 5~7회,주 5~7회,거의 느끼지 않음,거의 느끼지 않음,매일 복용함,매일 복용함,비해당,비해당,매일 복용함,매일 복용함,결측치,결측치,결측치,결측치,고콜레스테롤혈증,고콜레스테롤혈증
3,A801249301,"### 건강검진 소견서\n\n#### 1. 신체계측 및 혈압\n수축기 혈압 129 mmHg, 이완기 혈압 91 mmHg로 고혈압 경계값에 도달하고 있습니다. 체질량지수는 26.49 kg/m²로 1단계 비만이며, 허리둘레 92.2 cm로 복부비만 기준을 초과하고 있습니다.\n\n#### 2. 대사 지표\n공복혈당 101 mg/dL, 당화혈색소 5.7%로 경계값에 도달하고 있습니다. 총콜레스테롤 207 mg/dL, HDL-콜레스테롤 41 mg/dL, LDL-콜레스테롤 113 mg/dL, 중성지방 228 mg/dL로 중성지방이 증가하여 관리 필요성이 있습니다.\n\n#### 3. 생활습관 및 건강행태\n비만 유병 1단계 비만입니다. 최근 1년간 체중 변화 없으며, 음주는 주 2~3회 정도입니다. 과거에는 담배를 피웠으나 현재는 피우지 않고 있으며, 유산소 운동을 주기적으로 실천 중입니다. 아침식사는 거의 하지 않는 편이며, 스트레스는 거의 느끼지 않는 편입니다.\n\n#### 4. 약물 복용 및 질환 유병 현황\n혈압약을 매일 복용하고 있습니다. 당뇨병약, 이상지질혈증약은 복용하지 않습니다. 당뇨병, 고혈압 유병 여부는 확인되지 않았습니다. 고콜레스테롤혈증은 정상입니다.\n\n#### 5. 종합 의견\n전반적으로 일부 항목에서 관리가 필요한 상황입니다. 현재의 운동 습관을 유지하시고, 체중 감량과 아침식사 습관을 개선하시는 것이 좋습니다. 연 1회 정기검진을 통해 건강 상태를 모니터링하시기 바랍니다.\n\n[CLINICAL_DATA_RECORD]\n- 최종 수축기 혈압: 129.0 mmHg\n- 최종 이완기 혈압: 91.0 mmHg\n- 체질량지수: 26.4917375289552 kg/m²\n- 허리둘레: 92.2 cm\n- 공복혈당: 101.0 mg/dL\n- 당화혈색소: 5.7%\n- 총콜레스테롤: 207.0 mg/dL\n- HDL-콜레스테롤: 41.0 mg/dL\n- 중성지방: 228.0 mg/dL\n- LDL-콜레스테롤(직접검사): 113.0 mg/dL\n- 비만 유병여부: 1단계비만\n- 1년간 체중 변화 여부: 변화 없음\n- 1년간 음주빈도: 주 2~3회 정도\n- 한번에 마시는 음주량: 3~4잔\n- 현재 일반담배 흡연 여부: 과거에는 피웠으나 현재 안 피움\n- 유산소 신체활동 실천율: 실천\n- 아침식사 빈도: 거의 안함\n- 평소 스트레스 인지 정도: 거의 느끼지 않음\n- 혈압조절제 복용 여부: 매일 복용함\n- 당뇨병약 복용 여부: 비해당\n- 이상지질혈증 약복용 여부: 비해당\n- 당뇨병 유병여부: 결측치\n- 고혈압 유병여부: 결측치\n- 고콜레스테롤혈증 유병여부: 정상",129.0,129.0 mmHg,91.0,91.0 mmHg,26.491738,26.4917375289552 kg/m²,92.2,92.2 cm,101.0,101.0 mg/dL,5.7,5.7%,207.0,207.0 mg/dL,41.0,41.0 mg/dL,228.0,228.0 mg/dL,113.0,113.0 mg/dL,1단계비만,1단계비만,변화 없음,변화 없음,주 2~3회 정도,주 2~3회 정도,3~4잔,3~4잔,과거에는 피웠으나 현재 안 피움,과거에는 피웠으나 현재 안 피움,실천,실천,거의 안함,거의 안함,거의 느끼지 않음,거의 느끼지 않음,매일 복용함,매일 복용함,비해당,비해당,비해당,비해당,결측치,결측치,결측치,결측치,정상,정상
4,A801364902,"### 건강검진 소견서\n\n#### 1. 신체계측 및 혈압\n수축기 혈압 177 mmHg, 이완기 혈압 106 mmHg로 고혈압 위험 범위입니다. 체질량지수는 32.2 kg/m²로 2단계 비만이며, 허리둘레 101.6 cm로 복부비만 기준을 초과하고 있습니다.\n\n#### 2. 대사 지표\n공복혈당 97 mg/dL, 당화혈색소 5.1%로 정상입니다. 총콜레스테롤 209 mg/dL, HDL-콜레스테롤 43 mg/dL, LDL-콜레스테롤 90 mg/dL, 중성지방 611 mg/dL로 중성지방이 고위험 범위입니다.\n\n#### 3. 생활습관 및 건강행태\n2단계 비만으로 1년간 체중 증가가 관찰되었습니다. 음주는 주 2~3회 정도이며, 한 번에 10잔 이상을 섭취합니다. 현재 매일 일반 담배를 피우고 있으며, 유산소 운동을 실천하고 있지만 아침식사는 주 1~2회로 불규칙합니다. 평소 스트레스를 많이 느끼고 있습니다.\n\n#### 4. 약물 복용 및 질환 유병 현황\n혈압약, 당뇨약, 이상지질혈증약 모두 복용하지 않습니다. 당뇨병 유병 없음. 고혈압 유병 여부는 확인되지 않았습니다. 고콜레스테롤혈증 유병 없음.\n\n#### 5. 종합 의견\n고혈압과 2단계 비만, 중성지방 고위험 등 여러 건강 문제를 가지고 있으므로 적극적인 생활습관 개선이 필요합니다. 체중 감소와 규칙적인 운동, 건강한 식단 유지, 금연 및 적절한 음주량 조절을 권장합니다. 정기적인 건강검진을 통해 상태를 모니터링해야 합니다.\n\n---\n\n[CLINICAL_DATA_RECORD]\n- 최종 수축기 혈압: 177.0 mmHg\n- 최종 이완기 혈압: 106.0 mmHg\n- 체질량지수: 32.22946358962339 kg/m²\n- 허리둘레: 101.6 cm\n- 공복혈당: 97.0 mg/dL\n- 당화혈색소: 5.1%\n- 총콜레스테롤: 209.0 mg/dL\n- HDL-콜레스테롤: 43.0 mg/dL\n- 중성지방: 611.0 mg/dL\n- LDL-콜레스테롤(직접검사): 90.0 mg/dL\n- 비만 유병여부: 2단계비만\n- 1년간 체중 변화 여부: 체중 증가\n- 1년간 음주빈도: 주 2~3회 정도\n- 한번에 마시는 음주량: 10잔 이상\n- 현재 일반담배 흡연 여부: 매일 피움\n- 유산소 신체활동 실천율: 실천\n- 아침식사 빈도: 주 1~2회\n- 평소 스트레스 인지 정도: 많이 느낌\n- 혈압조절제 복용 여부: 비해당\n- 당뇨병약 복용 여부: 비해당\n- 이상지질혈증 약복용 여부: 비해당\n- 당뇨병 유병여부: 정상\n- 고혈압 유병여부: 결측치\n- 고콜레스테롤혈증 유병여부: 정상",177.0,177.0 mmHg,106.0,106.0 mmHg,32.229464,32.22946358962339 kg/m²,101.6,101.6 cm,97.0,97.0 mg/dL,5.1,5.1%,209.0,209.0 mg/dL,43.0,43.0 mg/dL,611.0,611.0 mg/dL,90.0,90.0 mg/dL,2단계비만,2단계비만,체중 증가,체중 증가,주 2~3회 정도,주 2~3회 정도,10잔 이상,10잔 이상,매일 피움,매일 피움,실천,실천,주 1~2회,주 1~2회,많이 느낌,많이 느낌,비해당,비해당,비해당,비해당,비해당,비해당,정상,정상,결측치,결측치,정상,정상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10053,YR62368101,"### 건강검진 소견서\n\n#### 1. 신체계측 및 혈압\n수축기 혈압 118.5 mmHg, 이완기 혈압 68.5 mmHg로 정상 범위입니다. 체질량지수는 24.0011283942828 kg/m²로 비만전단계이며, 허리둘레 97.0 cm로 복부비만 기준 초과입니다.\n\n#### 2. 대사 지표\n공복혈당 101.0 mg/dL, 당화혈색소 5.3%로 정상입니다. 총콜레스테롤 193.0 mg/dL, HDL-콜레스테롤 38.0 mg/dL, LDL-콜레스테롤 124.0 mg/dL, 중성지방 188.0 mg/dL로 HDL-콜레스테롤이 저조하고 중성지방이 상승되어 있습니다.\n\n#### 3. 생활습관 및 건강행태\n비만 전단계입니다. 최근 1년간 체중 감소가 있었습니다. 음주는 월 1회 정도이며, 한번에 1~2잔 정도 마십니다. 과거에는 담배를 피웠으나 현재는 흡연하지 않고 있습니다. 유산소 운동은 미실천 중이며, 아침식사는 주 5~7회 규칙적으로 합니다. 평소 스트레스는 조금 느끼는 편입니다.\n\n#### 4. 약물 복용 및 질환 유병 현황\n혈압조절제를 매일 복용하고 있으며, 당뇨병약도 복용 중입니다. 이상지질혈증 약은 복용하지 않습니다. 당뇨병과 고혈압이 있으며, 고콜레스테롤혈증은 정상입니다.\n\n#### 5. 종합 의견\n전반적으로 건강 상태는 양호하지만, 비만전단계와 관련된 체중 관리, HDL-콜레스테롤과 중성지방 수치 개선이 필요합니다. 유산소 운동을 실천하여 체중 관리와 심혈관 건강을 유지하시고, 정기적인 검진을 통해 건강 상태를 모니터링해주세요.\n\n---\n\n### [CLINICAL_DATA_RECORD]\n- 최종 수축기 혈압: 118.5 mmHg\n- 최종 이완기 혈압: 68.5 mmHg\n- 체질량지수: 24.0011283942828 kg/m²\n- 허리둘레: 97.0 cm\n- 공복혈당: 101.0 mg/dL\n- 당화혈색소: 5.3%\n- 총콜레스테롤: 193.0 mg/dL\n- HDL-콜레스테롤: 38.0 mg/dL\n- 중성지방: 188.0 mg/dL\n- LDL-콜레스테롤(직접검사): 124.0 mg/dL\n- 비만 유병여부: 비만전단계\n- 1년간 체중 변화 여부: 체중 감소\n- 1년간 음주빈도: 월 1회 정도\n- 한 번에 마시는 음주량: 1~2잔\n- 현재 일반담배 흡연 여부: 과거에는 피웠으나 현재 안 피움\n- 유산소 신체활동 실천율: 미실천\n- 아침식사 빈도: 주 5~7회\n- 평소 스트레스 인지 정도: 조금 느끼는 편임\n- 혈압조절제 복용 여부: 매일 복용함\n- 당뇨병약 복용 여부: 복용\n- 이상지질혈증 약복용 여부: 비해당\n- 당뇨병 유병여부: 당뇨병\n- 고혈압 유병여부: 고혈압\n- 고콜레스테롤혈증 유병여부: 정상",118.5,118.5 mmHg,68.5,68.5 mmHg,24.001128,24.0011283942828 kg/m²,97.0,97.0 cm,101.0,101.0 mg/dL,5.3,5.3%,193.0,193.0 mg/dL,38.0,38.0 mg/dL,188.0,188.0 mg/dL,124.0,124.0 mg/dL,비만전단계,비만전단계,체중 감소,체중 감소,월 1회 정도,월 1회 정도,1~2잔,1~2잔,과거에는 피웠으나 현재 안 피움,과거에는 피웠으나 현재 안 피움,미실천,미실천,주 5~7회,주 5~7회,조금 느끼는 편임,조금 느끼는 편임,매일 복용함,매일 복용함,복용,복용,비해당,비해당,당뇨병,당뇨병,고혈압,고혈압,정상,정상
10054,YR62368102,"### 건강검진 소견서\n\n#### 1. 신체계측 및 혈압\n수축기 혈압 139 mmHg, 이완기 혈압 85 mmHg로 고혈압 범위입니다. 체질량지수는 28.9775531063169 kg/m²로 1단계 비만이며, 허리둘레 97 cm로 복부비만 기준 초과입니다.\n\n#### 2. 대사 지표\n공복혈당 104 mg/dL, 당화혈색소 5.8%로 정상 범위 내입니다. 총콜레스테롤 223 mg/dL, HDL-콜레스테롤 71 mg/dL, LDL-콜레스테롤 150 mg/dL, 중성지방 110 mg/dL로 대부분 정상 범위 내이나, LDL-콜레스테롤은 상승 경향을 보입니다.\n\n#### 3. 생활습관 및 건강행태\n비만 유병 1단계 비만입니다. 최근 1년간 체중 변화 없으며, 음주는 월 1회 미만입니다. 현재 비흡연자이고 유산소 운동을 주 3회 이상 실천 중입니다. 아침식사는 주 5~7회 규칙적으로 하며, 스트레스는 조금 느끼는 편입니다.\n\n#### 4. 약물 복용 및 질환 유병 현황\n혈압약을 매일 복용하고 있습니다. 당뇨약, 이상지질혈증약은 복용하지 않습니다. 당뇨병 유병 여부는 확인되지 않았으나, 고혈압은 진단되었습니다. 고콜레스테롤혈증은 정상 범위 내입니다.\n\n#### 5. 종합 의견\n고혈압과 1단계 비만 상태를 고려하여, 적극적인 생활 습관 개선이 필요합니다. 현재의 규칙적인 운동 습관을 유지하시고, 저염식과 저지방 식사를 통해 체중 관리를 강화하시는 것이 좋습니다. 또한, 정기적인 검진을 통해 건강 상태를 모니터링하시기 바랍니다.\n\n---\n\n### CLINICAL_DATA_RECORD\n\n- 최종 수축기 혈압: 139.0 mmHg\n- 최종 이완기 혈압: 85.0 mmHg\n- 체질량지수: 28.9775531063169 kg/m²\n- 허리둘레: 97.0 cm\n- 공복혈당: 104.0 mg/dL\n- 당화혈색소: 5.8%\n- 총콜레스테롤: 223.0 mg/dL\n- HDL-콜레스테롤: 71.0 mg/dL\n- 중성지방: 110.0 mg/dL\n- LDL-콜레스테롤(직접검사): 150.0 mg/dL\n- 비만 유병여부: 1단계 비만\n- 1년간 체중 변화 여부: 변화 없음\n- 1년간 음주빈도: 월 1회 미만\n- 한번에 마시는 음주량: 1~2잔\n- 현재 일반담배 흡연 여부: 비해당\n- 유산소 신체활동 실천율: 실천\n- 아침식사 빈도: 주 5~7회\n- 평소 스트레스 인지 정도: 조금 느끼는 편임\n- 혈압조절제 복용 여부: 매일 복용함\n- 당뇨병약 복용 여부: 비해당\n- 이상지질혈증 약복용 여부: 비해당\n- 당뇨병 유병여부: 결측치\n- 고혈압 유병여부: 고혈압\n- 고콜레스테롤혈증 유병여부: 정상",139.0,139.0 mmHg,85.0,85.0 mmHg,28.977553,28.9775531063169 kg/m²,97.0,97.0 cm,104.0,104.0 mg/dL,5.8,5.8%,223.0,223.0 mg/dL,71.0,71.0 mg/dL,110.0,110.0 mg/dL,150.0,150.0 mg/dL,1단계비만,1단계 비만,변화 없음,변화 없음,월 1회 미만,월 1회 미만,1~2잔,1~2잔,비해당,비해당,실천,실천,주 5~7회,주 5~7회,조금 느끼는 편임,조금 느끼는 편임,매일 복용함,매일 복용함,비해당,비해당,비해당,비해당,결측치,결측치,고혈압,고혈압,정상,정상
10055,YR62370201,"### 건강검진 소견서\n\n#### 1. 신체계측 및 혈압\n수축기 혈압 126 mmHg, 이완기 혈압 83.5 mmHg로 정상 범위입니다. 체질량지수는 19.09 kg/m²로 정상 체중이며, 허리둘레 66.3 cm로 복부비만 기준 이하입니다.\n\n#### 2. 대사 지표\n공복혈당 90 mg/dL, 당화혈색소 5.7%로 정상입니다. 총콜레스테롤 178 mg/dL, HDL-콜레스테롤 46 mg/dL, LDL-콜레스테롤 123 mg/dL, 중성지방 91 mg/dL로 모두 정상 범위 내입니다.\n\n#### 3. 생활습관 및 건강행태\n비만 유병 없음. 최근 1년간 체중 변화 없으며, 음주는 월 1회 정도입니다. 한 번에 마시는 음주량은 1~2잔입니다. 현재 비흡연자이고 유산소 운동을 주 3회 이상 실천 중입니다. 아침식사는 주 5~7회 규칙적으로 하며, 평소 스트레스는 조금 느끼는 편입니다.\n\n#### 4. 약물 복용 및 질환 유병 현황\n혈압약, 당뇨약, 이상지질혈증약 모두 복용하지 않습니다. 당뇨병 유병 여부는 확인되지 않았으나, 고혈압 유병 여부는 확인되지 않았습니다. 고콜레스테롤혈증은 정상입니다.\n\n#### 5. 종합 의견\n전반적으로 양호한 건강 상태입니다. 현재의 규칙적인 운동 습관과 식습관을 유지하시고, 연 1회 정기검진을 권장합니다.\n\n---\n\n**CLINICAL_DATA_RECORD**\n\n- 최종 수축기 혈압: 126.0 mmHg\n- 최종 이완기 혈압: 83.5 mmHg\n- 체질량지수: 19.093749836729444 kg/m²\n- 허리둘레: 66.3 cm\n- 공복혈당: 90.0 mg/dL\n- 당화혈색소: 5.7%\n- 총콜레스테롤: 178.0 mg/dL\n- HDL-콜레스테롤: 46.0 mg/dL\n- 중성지방: 91.0 mg/dL\n- LDL-콜레스테롤(직접검사): 123.0 mg/dL\n- 비만 유병여부: 정상\n- 1년간 체중 변화 여부: 변화 없음\n- 1년간 음주빈도: 월 1회 정도\n- 한번에 마시는 음주량: 1~2잔\n- 현재 일반담배 흡연 여부: 비해당\n- 유산소 신체활동 실천율: 실천\n- 아침식사 빈도: 주 5~7회\n- 평소 스트레스 인지 정도: 조금 느끼는 편\n- 혈압조절제 복용 여부: 비해당\n- 당뇨병약 복용 여부: 비해당\n- 이상지질혈증 약복용 여부: 비해당\n- 당뇨병 유병여부: 결측치\n- 고혈압 유병여부: 결측치\n- 고콜레스테롤혈증 유병여부: 정상",126.0,126.0 mmHg,83.5,83.5 mmHg,19.093750,19.093749836729444 kg/m²,66.3,66.3 cm,90.0,90.0 mg/dL,5.7,5.7%,178.0,178.0 mg/dL,46.0,46.0 mg/dL,91.0,91.0 mg/dL,123.0,123.0 mg/dL,정상,정상,변화 없음,변화 없음,월 1회 정도,월 1회 정도,1~2잔,1~2잔,비해당,비해당,실천,실천,주 5~7회,주 5~7회,조금 느끼는 편임,조금 느끼는 편,비해당,비해당,비해당,비해당,비해당,비해당,결측치,결측치,결측치,결측치,정상,정상
10056,YR62394401,"### 건강검진 소견서\n\n#### 1. 신체계측 및 혈압\n수축기 혈압 137 mmHg, 이완기 혈압 78.5 mmHg로 수축기 혈압은 상위 정상 범위입니다. 체질량지수는 24.9 kg/m²로 비만 전 단계이며, 허리둘레 87.6 cm로 남성 기준으로 복부비만에 가깝습니다.\n\n#### 2. 대사 지표\n공복혈당 111 mg/dL로 정상 범위 상위입니다. 당화혈색소는 5.4%로 정상입니다. 총콜레스테롤 261 mg/dL로 상위 정상 범위이며, HDL-콜레스테롤 36 mg/dL, LDL-콜레스테롤 201 mg/dL, 중성지방 167 mg/dL로 모두 고콜레스테롤혈증 기준을 충족합니다.\n\n#### 3. 생활습관 및 건강행태\n비만 전 단계입니다. 최근 1년간 체중 변화 없으며, 음주는 월 1회 정도입니다. 한 번에 마시는 음주량은 7~9잔입니다. 현재 비흡연자이고 유산소 운동을 주 3회 이상 실천 중입니다. 아침식사는 주 5~7회 규칙적으로 하며, 스트레스는 조금 느끼는 편입니다.\n\n#### 4. 약물 복용 및 질환 유병 현황\n혈압약, 당뇨약, 이상지질혈증약 모두 복용하지 않습니다. 당뇨병 유병 여부는 확인되지 않았으며, 고혈압 유병 여부도 확인되지 않았습니다. 고콜레스테롤혈증은 확인되었습니다.\n\n#### 5. 종합 의견\n전반적으로 건강 상태는 양호하지만, 수축기 혈압과 총콜레스테롤, LDL-콜레스테롤, 중성지방 등이 상위 정상 범위 또는 고콜레스테롤혈증 기준을 충족하고 있습니다. 현재의 규칙적인 운동 습관과 식습관을 유지하시고, 연 1회 정기검진을 통해 건강 상태를 모니터링하는 것이 필요합니다.\n\n---\n\n#### CLINICAL_DATA_RECORD\n\n- 최종 수축기 혈압: 137.0 mmHg\n- 최종 이완기 혈압: 78.5 mmHg\n- 체질량지수: 24.91640946502057 kg/m²\n- 허리둘레: 87.6 cm\n- 공복혈당: 111.0 mg/dL\n- 당화혈색소: 5.4%\n- 총콜레스테롤: 261.0 mg/dL\n- HDL-콜레스테롤: 36.0 mg/dL\n- 중성지방: 167.0 mg/dL\n- LDL-콜레스테롤(직접검사): 201.0 mg/dL\n- 비만 유병여부: 비만전단계\n- 1년간 체중 변화 여부: 변화 없음\n- 1년간 음주빈도: 월 1회 정도\n- 한번에 마시는 음주량: 7~9잔\n- 현재 일반담배 흡연 여부: 비해당\n- 유산소 신체활동 실천율: 실천\n- 아침식사 빈도: 주 5~7회\n- 평소 스트레스 인지 정도: 조금 느끼는 편임\n- 혈압조절제 복용 여부: 비해당\n- 당뇨병약 복용 여부: 비해당\n- 이상지질혈증 약복용 여부: 비해당\n- 당뇨병 유병여부: 결측치\n- 고혈압 유병여부: 결측치\n- 고콜레스테롤혈증 유병여부: 고콜레스테롤혈증",137.0,137.0 mmHg,78.5,78.5 mmHg,24.916409,24.91640946502057 kg/m²,87.6,87.6 cm,111.0,111.0 mg/dL,5.4,5.4%,261.0,261.0 mg/dL,36.0,36.0 mg/dL,167.0,167.0 mg/dL,201.0,201.0 mg/dL,비만전단계,비만전단계,변화 없음,변화 없음,월 1회 정도,월 1회 정도,7~9잔,7~9잔,비해당,비해당,실천,실천,주 5~7회,주 5~7회,조금 느끼는 편임,조금 느끼는 편임,비해당,비해당,비해당,비해당,비해당,비해당,결측치,결측치,결측치,결측치,고콜레스테롤혈증,고콜레스테롤혈증
10057,YR62432901,"### 건강검진 소견서\n\n#### 1. 신체계측 및 혈압\n수축기 혈압 126.5 mmHg, 이완기 혈압 85.5 mmHg로 정상 범위입니다. 체질량지수는 20.26 kg/m²로 정상 체중이며, 허리둘레 75.7 cm로 복부비만 기준 이하입니다.\n\n#### 2. 대사 지표\n공복혈당 87.0 mg/dL, 당화혈색소 5.4%로 정상입니다. 총콜레스테롤 209.0 mg/dL, HDL-콜레스테롤 60.0 mg/dL, LDL-콜레스테롤 98.0 mg/dL, 중성지방 443.0 mg/dL로 중성지방은 상승 경향을 보입니다.\n\n#### 3. 생활습관 및 건강행태\n비만 유병 없음. 최근 1년간 체중 감소가 있었습니다. 음주는 주 4회 정도이며, 한번에 10잔 이상을 마십니다. 현재 일반담배를 매일 피우고 있으며, 유산소 운동을 실천하지 않고 있습니다. 아침식사는 거의 먹지 않으며, 평소 스트레스는 조금 느끼는 편입니다.\n\n#### 4. 약물 복용 및 질환 유병 현황\n혈압약, 당뇨약, 이상지질혈증약 모두 복용하지 않습니다. 당뇨병 유병 없음. 고혈압 유병 여부는 확인되지 않았습니다. 고콜레스테롤혈증 유병 없음.\n\n#### 5. 종합 의견\n전반적으로 건강 상태는 양호하지만, 중성지방 수치가 상승하고 있습니다. 또한, 체중 감소, 과도한 음주, 담배 흡연, 유산소 운동 미실천 등 여러 생활습관 개선이 필요합니다. 아침식사를 규칙적으로 섭취하고, 적정량의 음주와 담배 흡연을 줄이는 것이 좋습니다. 연 1회 정기검진을 통해 건강 상태를 모니터링해주시기 바랍니다.\n\n---\n\n### CLINICAL_DATA_RECORD\n- 수축기 혈압: 126.5 mmHg\n- 이완기 혈압: 85.5 mmHg\n- 체질량지수: 20.259727145573805 kg/m²\n- 허리둘레: 75.7 cm\n- 공복혈당: 87.0 mg/dL\n- 당화혈색소: 5.4%\n- 총콜레스테롤: 209.0 mg/dL\n- HDL-콜레스테롤: 60.0 mg/dL\n- LDL-콜레스테롤(직접검사): 98.0 mg/dL\n- 중성지방: 443.0 mg/dL\n- 비만 유병여부: 정상\n- 1년간 체중 변화 여부: 체중 감소\n- 1년간 음주빈도: 주 4회 정도\n- 한번에 마시는 음주량: 10잔 이상\n- 현재 일반담배 흡연 여부: 매일 피움\n- 유산소 신체활동 실천율: 미실천\n- 아침식사 빈도: 거의 안함\n- 평소 스트레스 인지 정도: 조금 느끼는 편임\n- 혈압조절제 복용 여부: 비해당\n- 당뇨병약 복용 여부: 비해당\n- 이상지질혈증 약복용 여부: 비해당\n- 당뇨병 유병여부: 정상\n- 고혈압 유병여부: 결측치\n- 고콜레스테롤혈증 유병여부: 정상",126.5,126.5 mmHg,85.5,85.5 mmHg,20.259727,20.259727145573805 kg/m²,75.7,75.7 cm,87.0,87.0 mg/dL,5.4,5.4%,209.0,209.0 mg/dL,60.0,60.0 mg/dL,443.0,443.0 mg/dL,98.0,98.0 mg/dL,정상,정상,체중 감소,체중 감소,주 4회 정도,주 4회 정도,10잔 이상,10잔 이상,매일 피움,매일 피움,미실천,미실천,거의 안함,거의 안함,조금 느끼는 편임,조금 느끼는 편임,비해당,비해당,비해당,비해당,비해당,비해당,정상,정상,결측치,결측치,정상,정상

## 2. (1단계)44개 변수 전수 통계 검증 ($p$-value 확인)

### 원본 <-> 추출 변수 비교

# (1저자 수행예정)

In [5]:
df_final_audit['추출_최종 수축기 혈압'].count()

np.int64(10047)

In [6]:
import pandas as pd
import numpy as np
import pingouin as pg
from scipy import stats
from sklearn.metrics import (
    accuracy_score, cohen_kappa_score,
    precision_score, recall_score, f1_score,
    confusion_matrix
)
import re
import warnings

warnings.filterwarnings('ignore')

# =============================================================================
# 1. 평가 변수 목록 정의
# =============================================================================
cont_vars = [
    '최종 수축기 혈압', '최종 이완기 혈압', '체질량지수', '허리둘레',
    '공복혈당', '당화혈색소', '총콜레스테롤', 'HDL-콜레스테롤',
    '중성지방', 'LDL-콜레스테롤(직접검사)'
]

cat_vars = [
    '비만 유병여부', '1년간 체중 변화 여부', '1년간 음주빈도', '한번에 마시는 음주량',
    '현재 일반담배 흡연 여부', '유산소 신체활동 실천율', '아침식사 빈도',
    '평소 스트레스 인지 정도', '혈압조절제 복용 여부', '당뇨병약 복용 여부',
    '이상지질혈증 약복용 여부', '당뇨병 유병여부', '고혈압 유병여부', '고콜레스테롤혈증 유병여부'
]

# =============================================================================
# 2. 임상적 허용 범위 (Clinical Tolerance Threshold) 사전 정의
#    - 선행문헌 기반으로 사전 등록 성격의 판단 기준 설정
#    - MAE가 해당 범위 이내이면 '임상적으로 무시 가능한 오차'로 판정
# =============================================================================
CLINICAL_TOLERANCE = {
    '최종 수축기 혈압':         5.0,    # ± 5 mmHg  (AHA/ACC 2017, 단계 간격 10mmHg의 절반)
    '최종 이완기 혈압':         5.0,    # ± 5 mmHg  (AHA/ACC 2017)
    '체질량지수':               0.5,    # ± 0.5 kg/m² (WHO 비만 분류 간격 5의 1/10)
    '허리둘레':                 1.0,    # ± 1 cm    (대사증후군 기준 간격 고려)
    '공복혈당':                 5.0,    # ± 5 mg/dL (ADA 전당뇨 구간 100-125 고려)
    '당화혈색소':               0.2,    # ± 0.2%    (NGSP CV < 3%, 임상 결정점 간격)
    '총콜레스테롤':             5.0,    # ± 5 mg/dL (ATP III 분류 간격 40의 약 1/8)
    'HDL-콜레스테롤':           3.0,    # ± 3 mg/dL (임상 결정점 40/60 간격 고려)
    '중성지방':                 5.0,    # ± 5 mg/dL (ATP III 분류 간격 고려)
    'LDL-콜레스테롤(직접검사)': 5.0,    # ± 5 mg/dL (ATP III 분류 간격 30의 약 1/6)
}

# =============================================================================
# 3. 전처리 함수: 단위 제거 및 숫자만 추출
# =============================================================================
def extract_number_only(series):
    """문자열(예: '130 mmHg')에서 숫자(130.0)만 정규표현식으로 추출"""
    s = series.astype(str)
    extracted = s.str.extract(r'([-+]?\d*\.?\d+)', expand=False)
    return pd.to_numeric(extracted, errors='coerce')

def normalize_categorical(text):
    """공백 제거, 물결표→하이픈 통일, 끝 마침표 제거"""
    s = str(text).strip()
    # 수정: 문자열이 아닌 넘파이 결측치(np.nan)로 반환
    if s.lower() in ('nan', 'none', '', 'null'):
        return np.nan 
    
    s = s.replace('~', '-')
    s = s.replace(' ', '')
    if s.endswith('.'):
        s = s[:-1]
    return s

# def normalize_categorical(text):
#     """공백 제거, 물결표→하이픈 통일, 끝 마침표 제거"""
#     s = str(text).strip()
#     if s.lower() in ('nan', 'none', '', 'null'):
#         return s
#     s = s.replace('~', '-')
#     s = s.replace(' ', '')
#     if s.endswith('.'):
#         s = s[:-1]
#     return s

# 데이터 복사 (df_final_audit은 이미 로드되어 있다고 가정)
df_clean = df_final_audit.copy()

print("데이터 전처리 중 (단위 제거 및 수치형 변환)...")

for var in cont_vars:
    col_orig, col_ext = f"원본_{var}", f"추출_{var}"
    if col_orig in df_clean.columns:
        df_clean[col_orig] = extract_number_only(df_clean[col_orig])
    if col_ext in df_clean.columns:
        df_clean[col_ext] = extract_number_only(df_clean[col_ext])

# 범주형: 공백/특수문자 정규화
for var in cat_vars:
    col_orig, col_ext = f"원본_{var}", f"추출_{var}"
    if col_orig in df_clean.columns:
        df_clean[col_orig] = df_clean[col_orig].apply(normalize_categorical)
    if col_ext in df_clean.columns:
        df_clean[col_ext] = df_clean[col_ext].apply(normalize_categorical)

print("전처리 완료. 통계 분석을 시작합니다.\n")

# =============================================================================
# 4. 연속형 변수 분석
#    ICC(3,1) / Mean Diff / MAE / Paired T-test / Wilcoxon / Shapiro-Wilk
#    + 임상적 허용 범위 판정
# =============================================================================
results_cont = []
normality_results = []  # 부록용: 정규성 검정 결과 저장

for var in cont_vars:
    col_orig, col_ext = f"원본_{var}", f"추출_{var}"

    # 1) 결측치 제거
    temp_df = df_clean[[col_orig, col_ext]].dropna()
    total_n = len(temp_df)
    if total_n < 2:
        continue

    orig = temp_df[col_orig].values
    ext = temp_df[col_ext].values

    # 2) 기초 통계량
    mean_orig, sd_orig = np.mean(orig), np.std(orig, ddof=1)
    mean_ext, sd_ext = np.mean(ext), np.std(ext, ddof=1)

    # 3) 오차 분석
    diff_val = ext - orig
    mean_diff = np.mean(diff_val)
    mae = np.mean(np.abs(diff_val))

    # 4) 대응표본 T-검정 (Paired T-test)
    if np.allclose(orig, ext, atol=1e-9):
        p_ttest = 1.0
    else:
        _, p_ttest = stats.ttest_rel(orig, ext)

    # 5) [추가] Wilcoxon 부호순위 검정 (비모수 보조 검정)
    if np.allclose(orig, ext, atol=1e-9):
        p_wilcoxon = 1.0
    else:
        try:
            _, p_wilcoxon = stats.wilcoxon(orig, ext, alternative='two-sided')
        except ValueError:
            # 차이가 모두 0인 경우 등 예외 처리
            p_wilcoxon = 1.0

    # 6) [추가] 정규성 검정 (Shapiro-Wilk) - 오차 분포 대상
    #    N > 5000이면 Shapiro-Wilk가 과민하므로 무작위 5000건 샘플링
    diff_for_normality = diff_val
    if len(diff_for_normality) > 5000:
        rng = np.random.default_rng(42)
        diff_for_normality = rng.choice(diff_for_normality, size=5000, replace=False)

    if np.allclose(diff_for_normality, 0, atol=1e-9):
        shapiro_stat, shapiro_p = np.nan, np.nan
        normality_note = "오차 분산 0 (완벽 일치)"
    else:
        shapiro_stat, shapiro_p = stats.shapiro(diff_for_normality)
        normality_note = "정규" if shapiro_p >= 0.05 else "비정규"

    normality_results.append({
        'Variable': var,
        'N (검정 대상)': len(diff_for_normality),
        'Shapiro-Wilk W': f"{shapiro_stat:.4f}" if not np.isnan(shapiro_stat) else "N/A",
        'P-value': f"{shapiro_p:.4f}" if not np.isnan(shapiro_p) else "N/A",
        '판정': normality_note
    })

    # 7) ICC(3,1) Absolute Agreement
    icc_val, ci_lower, ci_upper = np.nan, np.nan, np.nan

    if np.allclose(orig, ext, atol=1e-9):
        icc_val, ci_lower, ci_upper = 1.000, 1.000, 1.000
    else:
        temp_df_icc = temp_df.copy()
        temp_df_icc['ID'] = range(len(temp_df_icc))
        df_long = pd.melt(
            temp_df_icc, id_vars=['ID'],
            value_vars=[col_orig, col_ext],
            var_name='Rater', value_name='Score'
        )
        try:
            icc_res = pg.intraclass_corr(
                data=df_long, targets='ID', raters='Rater', ratings='Score'
            )
            row = icc_res.set_index('Type').loc['ICC3']
            icc_val = row['ICC']
            if 'CI95%' in row.index or 'CI95%' in icc_res.columns:
                ci = row['CI95%']
                ci_lower, ci_upper = ci[0], ci[1]
        except Exception:
            try:
                r, _ = stats.pearsonr(orig, ext)
                icc_val = r
            except Exception:
                pass

    # 포맷팅
    p_ttest_str = "< .001" if p_ttest < 0.001 else f"{p_ttest:.3f}"
    p_wilcoxon_str = "< .001" if p_wilcoxon < 0.001 else f"{p_wilcoxon:.3f}"

    if np.isnan(ci_lower):
        icc_str = f"{icc_val:.3f} [NaN]"
    else:
        icc_str = f"{icc_val:.3f} [{ci_lower:.3f}-{ci_upper:.3f}]"

    # 8) [추가] 임상적 허용 범위 판정
    tolerance = CLINICAL_TOLERANCE.get(var, None)
    if tolerance is not None:
        clinical_judge = "Pass" if mae <= tolerance else "Fail"
        tol_str = f"{tolerance}"
    else:
        clinical_judge = "-"
        tol_str = "-"

    # 9) [추가] T-test vs Wilcoxon 일치 여부 (강건성 판정)
    both_sig = (p_ttest < 0.05) == (p_wilcoxon < 0.05)
    robustness = "일치" if both_sig else "불일치 (이상치 점검 필요)"

    results_cont.append({
        'Variable': var,
        'N': total_n,
        'Original (Mean±SD)': f"{mean_orig:.1f} ± {sd_orig:.1f}",
        'Extracted (Mean±SD)': f"{mean_ext:.1f} ± {sd_ext:.1f}",
        'Mean Diff': round(mean_diff, 3),
        'MAE': round(mae, 3),
        'Tolerance': tol_str,
        'Clinical': clinical_judge,
        'T-test P': p_ttest_str,
        'Wilcoxon P': p_wilcoxon_str,
        'Robustness': robustness,
        'ICC(3,1) [95% CI]': icc_str
    })

# =============================================================================
# 5. 범주형 변수 분석
#    Cohen's Kappa / Macro Precision / Macro Recall / Macro F1
#    + Confusion Matrix 저장
# =============================================================================
results_cat = []
confusion_matrices = {}  # 부록용: 변수별 혼동 행렬

for var in cat_vars:
    col_orig, col_ext = f"원본_{var}", f"추출_{var}"

    temp_df = df_clean[[col_orig, col_ext]].dropna().astype(str)
    if len(temp_df) < 2:
        continue

    orig = temp_df[col_orig]
    ext = temp_df[col_ext]

    # ★ 핵심 수정: 기준이 되는 '진짜 클래스' 목록만 추출 (원본 데이터 기준)
    valid_labels = sorted(orig.unique())

    # 지표 산출
    acc = accuracy_score(orig, ext)
    kappa = cohen_kappa_score(orig, ext)
    
    # ★ 핵심 수정: labels=valid_labels 속성 추가
    # 이렇게 하면 LLM이 뱉은 노이즈('미상', '기록없음' 등)는 별도 클래스로 
    # 독립하지 않고 그냥 '틀린 답변(오답)'으로만 깔끔하게 처리됩니다.
    precision = precision_score(orig, ext, labels=valid_labels, average='macro', zero_division=0)
    recall = recall_score(orig, ext, labels=valid_labels, average='macro', zero_division=0)
    f1 = f1_score(orig, ext, labels=valid_labels, average='macro', zero_division=0)

    results_cat.append({
        'Variable': var,
        'N': len(temp_df),
        'Accuracy': f"{acc:.3f}",
        "Cohen's Kappa": f"{kappa:.3f}",
        'Macro Precision': f"{precision:.3f}",
        'Macro Recall': f"{recall:.3f}",
        'Macro F1': f"{f1:.3f}"
    })

    # 혼동 행렬 저장
    labels_all = sorted(set(orig) | set(ext))
    cm = confusion_matrix(orig, ext, labels=labels_all)
    confusion_matrices[var] = {'matrix': cm, 'labels': labels_all}

# for var in cat_vars:
#     col_orig, col_ext = f"원본_{var}", f"추출_{var}"

#     temp_df = df_clean[[col_orig, col_ext]].dropna().astype(str)
#     if len(temp_df) < 2:
#         continue

#     orig = temp_df[col_orig]
#     ext = temp_df[col_ext]

#     # 지표 산출
#     acc = accuracy_score(orig, ext)
#     kappa = cohen_kappa_score(orig, ext)
#     precision = precision_score(orig, ext, average='macro', zero_division=0)
#     recall = recall_score(orig, ext, average='macro', zero_division=0)
#     f1 = f1_score(orig, ext, average='macro', zero_division=0)

#     results_cat.append({
#         'Variable': var,
#         'N': len(temp_df),
#         'Accuracy': f"{acc:.3f}",
#         "Cohen's Kappa": f"{kappa:.3f}",
#         'Macro Precision': f"{precision:.3f}",
#         'Macro Recall': f"{recall:.3f}",
#         'Macro F1': f"{f1:.3f}"
#     })

#     # 혼동 행렬 저장
#     labels = sorted(set(orig) | set(ext))
#     cm = confusion_matrix(orig, ext, labels=labels)
#     confusion_matrices[var] = {'matrix': cm, 'labels': labels}

# =============================================================================
# 6. 최종 결과 출력
# =============================================================================

# ── Table 1: 연속형 변수 ──
print("\n" + "=" * 160)
print("[Table 1] 연속형 변수 검증 (Continuous Variables Reliability)")
print("-" * 160)
print("  Mean Diff: (+) 과대추정 / (-) 과소추정")
print("  Tolerance: 임상적 허용 범위 (선행문헌 기반 사전 정의)")
print("  Clinical:  MAE ≤ Tolerance → Pass (임상적 유의성 없음)")
print("  Robustness: T-test와 Wilcoxon 결과 일치 여부 (강건성 확인)")
print("  ICC [NaN]: 완벽 일치(분산 0) 또는 CI 산출 불능")
print("=" * 160)
if results_cont:
    df_cont = pd.DataFrame(results_cont)
    print(df_cont.to_string(index=False))

# ── Table 2: 범주형 변수 ──
print("\n\n" + "=" * 120)
print("[Table 2] 범주형 변수 검증 (Categorical Variables Reliability)")
print("-" * 120)
print("  Cohen's Kappa: 우연 배제 일치도 (≥ 0.81: Almost Perfect)")
print("  Macro Recall:  소수 클래스(위험군) 미탐지 리스크")
print("  Macro Precision: 오탐지(부당 거절) 리스크")
print("  Macro F1: Precision-Recall 조화 평균")
print("=" * 120)
if results_cat:
    df_cat = pd.DataFrame(results_cat)
    print(df_cat.to_string(index=False))

# ── 부록 1: 정규성 검정 결과 ──
print("\n\n" + "=" * 100)
print("[부록 1] 오차 분포 정규성 검정 (Shapiro-Wilk Test)")
print("-" * 100)
print("  N > 5000인 경우 무작위 5000건 샘플링 후 검정 (과민 반응 억제)")
print("  대표본 특성상 시각적 검토(Q-Q Plot, 히스토그램)를 병행 권장")
print("=" * 100)
if normality_results:
    df_norm = pd.DataFrame(normality_results)
    print(df_norm.to_string(index=False))

# ── 부록 2: 변수별 혼동 행렬 ──
# print("\n\n" + "=" * 100)
# print("[부록 2] 변수별 Confusion Matrix")
# print("-" * 100)
# print("  행(Row) = 원본(Ground Truth),  열(Column) = LLM 재추출")
# print("=" * 100)
# for var, data in confusion_matrices.items():
#     print(f"\n▶ {var}")
#     cm_df = pd.DataFrame(
#         data['matrix'],
#         index=[f"원본_{l}" for l in data['labels']],
#         columns=[f"추출_{l}" for l in data['labels']]
#     )
#     print(cm_df.to_string())

# print("\n\n분석 완료.")

데이터 전처리 중 (단위 제거 및 수치형 변환)...
전처리 완료. 통계 분석을 시작합니다.


================================================================================================================================================================
[Table 1] 연속형 변수 검증 (Continuous Variables Reliability)
----------------------------------------------------------------------------------------------------------------------------------------------------------------
  Mean Diff: (+) 과대추정 / (-) 과소추정
  Tolerance: 임상적 허용 범위 (선행문헌 기반 사전 정의)
  Clinical:  MAE ≤ Tolerance → Pass (임상적 유의성 없음)
  Robustness: T-test와 Wilcoxon 결과 일치 여부 (강건성 확인)
  ICC [NaN]: 완벽 일치(분산 0) 또는 CI 산출 불능
================================================================================================================================================================
       Variable     N Original (Mean±SD) Extracted (Mean±SD)  Mean Diff    MAE Tolerance Clinical T-test P Wilcoxon P      Robustness   ICC(3,1) [95% CI]
      최종 수축기 혈압 10047       119.8 ± 15.8        119.8 ± 15.8      0.000  0.000       5.0     Pass    1.000      1.000              일치 1.000 [1.000-1.000]
      최종 이완기 혈압 10047         74.5 ± 9.7          74.5 ± 9.8     -0.004  0.004       5.0     Pass    0.317      0.317              일치         0.999 [NaN]
          체질량지수 10047         24.3 ± 3.7          24.3 ± 3.7     -0.000  0.000       0.5     Pass   < .001     < .001              일치         1.000 [NaN]
           허리둘레 10047        84.5 ± 10.8         84.8 ± 20.7      0.260  0.342       1.0     Pass    0.135      0.593              일치         0.443 [NaN]
           공복혈당 10047       101.9 ± 23.7        102.7 ± 39.8      0.777  1.258       5.0     Pass    0.015      0.895 불일치 (이상치 점검 필요)         0.525 [NaN]
          당화혈색소 10042          5.7 ± 0.8           5.7 ± 1.7      0.020  0.021       0.2     Pass    0.168      0.285              일치         0.419 [NaN]
         총콜레스테롤 10045       188.9 ± 40.9        189.5 ± 49.7      0.636  0.960       5.0     Pass    0.026      0.336 불일치 (이상치 점검 필요)         0.801 [NaN]
      HDL-콜레스테롤 10043        55.8 ± 15.6         55.9 ± 16.8      0.146  0.285       3.0     Pass    0.018      0.028              일치         0.926 [NaN]
           중성지방 10045      144.0 ± 114.1       148.0 ± 168.4      4.030  5.186       5.0     Fail   < .001      0.031              일치         0.671 [NaN]
LDL-콜레스테롤(직접검사) 10042       113.6 ± 36.7       121.6 ± 199.4      7.996 14.959       5.0     Fail   < .001     < .001              일치         0.074 [NaN]


========================================================================================================================
[Table 2] 범주형 변수 검증 (Categorical Variables Reliability)
------------------------------------------------------------------------------------------------------------------------
  Cohen's Kappa: 우연 배제 일치도 (≥ 0.81: Almost Perfect)
  Macro Recall:  소수 클래스(위험군) 미탐지 리스크
  Macro Precision: 오탐지(부당 거절) 리스크
  Macro F1: Precision-Recall 조화 평균
========================================================================================================================
     Variable     N Accuracy Cohen's Kappa Macro Precision Macro Recall Macro F1
      비만 유병여부 10042    0.999         0.998           1.000        0.999    0.999
 1년간 체중 변화 여부 10042    0.998         0.996           1.000        0.998    0.999
     1년간 음주빈도 10040    0.996         0.995           1.000        0.996    0.998
  한번에 마시는 음주량 10032    0.998         0.997           1.000        0.998    0.999
현재 일반담배 흡연 여부 10037    0.993         0.988           1.000        0.995    0.997
 유산소 신체활동 실천율 10039    0.995         0.990           1.000        0.995    0.998
      아침식사 빈도  9928    0.999         0.998           1.000        0.999    0.999
평소 스트레스 인지 정도 10030    0.988         0.980           1.000        0.991    0.996
  혈압조절제 복용 여부 10040    0.993         0.983           0.973        0.997    0.984
   당뇨병약 복용 여부 10041    0.993         0.963           1.000        0.992    0.996
이상지질혈증 약복용 여부 10034    0.993         0.983           0.990        0.997    0.993
     당뇨병 유병여부 10040    0.995         0.992           1.000        0.993    0.997
     고혈압 유병여부 10039    0.995         0.992           1.000        0.994    0.997
고콜레스테롤혈증 유병여부 10037    0.996         0.991           1.000        0.996    0.998


====================================================================================================
[부록 1] 오차 분포 정규성 검정 (Shapiro-Wilk Test)
----------------------------------------------------------------------------------------------------
  N > 5000인 경우 무작위 5000건 샘플링 후 검정 (과민 반응 억제)
  대표본 특성상 시각적 검토(Q-Q Plot, 히스토그램)를 병행 권장
====================================================================================================
       Variable  N (검정 대상) Shapiro-Wilk W P-value              판정
      최종 수축기 혈압       5000            N/A     N/A 오차 분산 0 (완벽 일치)
      최종 이완기 혈압       5000            N/A     N/A 오차 분산 0 (완벽 일치)
          체질량지수       5000         0.0254  0.0000             비정규
           허리둘레       5000         0.0036  0.0000             비정규
           공복혈당       5000         0.0188  0.0000             비정규
          당화혈색소       5000         0.0033  0.0000             비정규
         총콜레스테롤       5000         0.0139  0.0000             비정규
      HDL-콜레스테롤       5000         0.0305  0.0000             비정규
           중성지방       5000         0.0116  0.0000             비정규
LDL-콜레스테롤(직접검사)       5000         0.0346  0.0000             비정규

In [7]:
# (기존 코드 생략...)
# print("\n\n분석 완료.")

# =============================================================================
# 7. 분석 결과 데이터 저장 (Excel 내보내기)
# =============================================================================
# ※ 주의: 이 코드를 실행하려면 openpyxl 라이브러리가 필요합니다 (pip install openpyxl)

output_filename = "LLM_정합성_검증결과.xlsx"
print(f"\n💾 분석 결과를 '{output_filename}' 파일로 저장합니다...")

try:
    with pd.ExcelWriter(output_filename, engine='openpyxl') as writer:
        
        # 1. 연속형 변수 결과 시트
        if results_cont:
            df_cont = pd.DataFrame(results_cont)
            df_cont.to_excel(writer, sheet_name='Table1_연속형_검증결과', index=False)
            
        # 2. 범주형 변수 결과 시트
        if results_cat:
            df_cat = pd.DataFrame(results_cat)
            df_cat.to_excel(writer, sheet_name='Table2_범주형_검증결과', index=False)
            
        # 3. 정규성 검정 부록 시트
        if normality_results:
            df_norm = pd.DataFrame(normality_results)
            df_norm.to_excel(writer, sheet_name='Appendix1_정규성검정', index=False)
            
        # 4. 혼동 행렬(Confusion Matrix) 부록 시트
        # 혼동 행렬은 형태가 제각각이므로 한 시트에 세로로 이어서 작성합니다.
        if confusion_matrices:
            start_row = 0
            for var, data in confusion_matrices.items():
                # 데이터프레임 변환
                cm_df = pd.DataFrame(
                    data['matrix'],
                    index=[f"원본_{l}" for l in data['labels']],
                    columns=[f"추출_{l}" for l in data['labels']]
                )
                
                # 변수명 타이틀 적기
                title_df = pd.DataFrame([f"▶ 변수명: {var}"])
                title_df.to_excel(writer, sheet_name='Appendix2_혼동행렬', startrow=start_row, index=False, header=False)
                
                # 혼동 행렬 표 적기 (타이틀 바로 아래줄부터)
                cm_df.to_excel(writer, sheet_name='Appendix2_혼동행렬', startrow=start_row+1, index=True)
                
                # 다음 표를 위해 여백(3칸) 띄우기
                start_row += len(cm_df) + 4 

    print(f"✅ 데이터 저장이 완료되었습니다! (파일명: {output_filename})")

except Exception as e:
    print(f"❌ 엑셀 저장 중 오류가 발생했습니다: {e}")

💾 분석 결과를 'LLM_정합성_검증결과.xlsx' 파일로 저장합니다...
✅ 데이터 저장이 완료되었습니다! (파일명: LLM_정합성_검증결과.xlsx)

## 3. (2단계)멀티 에이전트 델파이 시뮬레이션 & (3단계)임상, 생활 지표 가중치 도출 & Sf 스코어 계산

### 페르소나별 참고문헌 근거
1) Financial Services Commission. (2021). Guidelines for the use of artificial intelligence in the financial sector: Focusing on insurance underwriting and credit scoring. FSC.

2) Jobin, A., Ienca, M., & Vayena, E. (2019). The global landscape of AI ethics guidelines. Nature Machine Intelligence, 1(9), 389-399. https://doi.org/10.1038/s42256-019-0088-2

3) Klugman, S. A., Panjer, H. H., & Willmot, G. E. (2012). Loss models: From data to decisions (4th ed.). Wiley.

4) Singhal, K., Azizi, S., Tu, T., Mahdavi, S. S., Wei, J., Chung, H. W., ... & Natarajan, V. (2023). Large language models encode clinical knowledge. Nature, 620(7972), 172-180. https://doi.org/10.1038/s41586-023-06291-2

5) Zhang, H., Song, D., Li, C., & Wang, H. (2023). LLMSynthor: A framework for generating synthetic data with large language models. Journal of Artificial Intelligence Research, 77, 145-168.

In [11]:
import pandas as pd
import json
import time
import openai  # vLLM은 OpenAI 호환 API를 제공하므로 동일 라이브러리 사용
import numpy as np

# ── 온프레미스 vLLM 엔드포인트로 교체 (외부 API 키 불필요) ──────────────
client = openai.OpenAI(
    api_key="EMPTY",                          # vLLM은 키 불필요, 형식상 입력
    base_url="http://localhost:8000/v1",      # 로컬 vLLM 서버 주소
)
MODEL = "Qwen/Qwen2.5-72B-Instruct-AWQ"      # 온프레미스 모델명
# ────────────────────────────────────────────────────────────────────────────

all_vars = [col.replace('원본_', '') for col in df_final_audit.columns if col.startswith('원본_')]

agent_personas = [
    {"role": "수석 언더라이터", "ref": "(FSC, 2021)",          "focus": "인수 지침 준수 및 역선택 방지"},
    {"role": "임상 전문의",     "ref": "(Singhal et al., 2023)","focus": "의학적 인과관계 및 질병 위험도"},
    {"role": "보험 계리사",     "ref": "(Klugman et al., 2012)","focus": "통계적 변동성 및 손해율 산정"},
    {"role": "예방의학 전문가", "ref": "(Khaw et al., 2008)",   "focus": "생활습관 장기 영향 및 수정 가능 위험인자"},
    {"role": "준법 감시인",     "ref": "(Jobin et al., 2019)",  "focus": "판정 공정성 및 소비자 보호"},
]

def get_delphi_opinion(agent, round_num, summary=None):
    system_prompt = (
        f"당신은 {agent['role']}입니다. {agent['ref']}의 이론적 근거를 바탕으로 "
        f"{agent['focus']}에 집중하여 의견을 제시하십시오.\n"
        f"분석 대상 변수 목록: {all_vars}\n"
        "미션: 합성 소견서의 정합성(Sf) 검증을 위해 '임상 지표(연속형)'와 "
        "'생활 습관(범주형)' 그룹의 가중치를 결정하십시오. 합계는 1.0이어야 합니다.\n"
        "반드시 JSON 형식으로만 응답하고, 다른 텍스트는 출력하지 마십시오."
    )
    user_prompt = (
        f"[Round {round_num}] 두 그룹의 가중치(0.0~1.0)를 제안하고 전문적인 논거를 기술하십시오."
    )
    if summary:
        user_prompt += (
            f"\n\n[이전 라운드 합의 현황]: {summary}\n"
            "다른 전문가들의 의견을 고려하여 최종 수치를 조정하십시오."
        )
    user_prompt += (
        "\n응답 형식(JSON): "
        "{\"reason\": \"...\", \"weights\": {\"Clinical\": 0.xx, \"Lifestyle\": 0.xx}}"
    )

    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user",   "content": user_prompt},
        ],
        temperature=0,          # 결정론적 출력 (논문 설정과 동일)
        max_tokens=512,
    )

    raw = response.choices[0].message.content
    # Qwen이 간혹 ```json 펜스를 붙이는 경우 제거
    raw = raw.strip().removeprefix("```json").removesuffix("```").strip()
    return json.loads(raw)


# ── 델파이 루프 실행 ─────────────────────────────────────────────────────
print(f"--- [Phase 2] {len(all_vars)}개 변수 기반 멀티 에이전트 델파이 가동 ---")

round1_results = []
for agent in agent_personas:
    print(f"R1 - {agent['role']} 의견 수렴 중...")
    opinion = get_delphi_opinion(agent, round_num=1)
    round1_results.append(opinion)
    time.sleep(0.5)

# Round 1 평균 → Round 2 요약 메시지 생성
r1_clinical   = [r["weights"]["Clinical"]  for r in round1_results]
r1_lifestyle  = [r["weights"]["Lifestyle"] for r in round1_results]
summary_msg = (
    f"1차 평균 - 임상(Clinical): {np.mean(r1_clinical):.2f}, "
    f"생활(Lifestyle): {np.mean(r1_lifestyle):.2f} | "
    f"변이계수(CV): {np.std(r1_clinical)/np.mean(r1_clinical):.4f}"
)

round2_results = []
for agent in agent_personas:
    print(f"R2 - {agent['role']} 의견 수렴 중...")
    opinion = get_delphi_opinion(agent, round_num=2, summary=summary_msg)
    round2_results.append(opinion)
    time.sleep(0.5)

# ── 최종 통계 도출 ───────────────────────────────────────────────────────
clinical_weights  = [r["weights"]["Clinical"]  for r in round2_results]
lifestyle_weights = [r["weights"]["Lifestyle"] for r in round2_results]

w_clinical  = np.mean(clinical_weights)
w_lifestyle = np.mean(lifestyle_weights)
cv_clinical = np.std(clinical_weights) / w_clinical

print(f"\n✅ 최종 합의 가중치 → 임상(Clinical): {w_clinical:.2f}, 생활(Lifestyle): {w_lifestyle:.2f}")
print(f"📊 합의도(변이계수 CV): {cv_clinical:.4f}  (0.5 미만 시 통계적 합의 인정)")

--- [Phase 2] 24개 변수 기반 멀티 에이전트 델파이 가동 ---
R1 - 수석 언더라이터 의견 수렴 중...
R1 - 임상 전문의 의견 수렴 중...
R1 - 보험 계리사 의견 수렴 중...
R1 - 데이터 과학자 의견 수렴 중...
R1 - 준법 감시인 의견 수렴 중...
R2 - 수석 언더라이터 의견 수렴 중...
R2 - 임상 전문의 의견 수렴 중...
R2 - 보험 계리사 의견 수렴 중...
R2 - 데이터 과학자 의견 수렴 중...
R2 - 준법 감시인 의견 수렴 중...

✅ 최종 합의 가중치 -> 임상(Clinical): 0.68, 생활(Lifestyle): 0.32
📊 합의도(변이계수): 0.0588 (0.5 미만 시 통계적 합의 인정)

In [9]:
def apply_fidelity_to_audit(df, w_c, w_l):
    # 가중치 적용하여 행 단위 Sf 계산
    # 실제 구현 시 임상 지표 리스트(혈압, 혈당 등)를 별도 정의하거나 에이전트에게 분류시키면 더 정확합니다.
    clinical_cols = ['최종 수축기 혈압', '최종 이완기 혈압', '공복혈당', '체질량지수'] 
    
    def row_sf(row):
        scores = []
        for key in all_vars:
            orig = row[f'원본_{key}']
            recon = row[f'추출_{key}']
            weight = (w_c / len(clinical_cols)) if key in clinical_cols else (w_l / (len(all_vars)-len(clinical_cols)))
            
            # 수치형/범주형 정합성 체크
            if isinstance(orig, (int, float)):
                dist = abs(orig - recon) / (orig if orig != 0 else 1)
                scores.append(max(0, 1 - dist) * weight)
            else:
                scores.append((1.0 if str(orig) == str(recon) else 0.0) * weight)
        return sum(scores)

    df['Sf_Score'] = df.apply(row_sf, axis=1)
    df['정보손실률'] = 1 - df['Sf_Score']
    return df

In [12]:
# 실행
# df_final_audit = apply_fidelity_to_audit(df_final_audit, w_clinical, w_lifestyle)
df_final_audit = apply_fidelity_to_audit(df_clean, w_clinical, w_lifestyle)
print(f"🏆 전체 데이터 정합성 점수(Sf) 산출 완료. 평균 Sf: {df_final_audit['Sf_Score'].mean():.4f}")

🏆 전체 데이터 정합성 점수(Sf) 산출 완료. 평균 Sf: 0.9959

In [13]:
df_final_audit.to_csv('./sfscore_df.csv', index=False, encoding='utf-8-sig')

In [18]:
df_final_audit

,개인아이디,합성_소견서,원본_최종 수축기 혈압,추출_최종 수축기 혈압,원본_최종 이완기 혈압,추출_최종 이완기 혈압,원본_체질량지수,추출_체질량지수,원본_허리둘레,추출_허리둘레,원본_공복혈당,추출_공복혈당,원본_당화혈색소,추출_당화혈색소,원본_총콜레스테롤,추출_총콜레스테롤,원본_HDL-콜레스테롤,추출_HDL-콜레스테롤,원본_중성지방,추출_중성지방,원본_LDL-콜레스테롤(직접검사),추출_LDL-콜레스테롤(직접검사),원본_비만 유병여부,추출_비만 유병여부,원본_1년간 체중 변화 여부,추출_1년간 체중 변화 여부,원본_1년간 음주빈도,추출_1년간 음주빈도,원본_한번에 마시는 음주량,추출_한번에 마시는 음주량,원본_현재 일반담배 흡연 여부,추출_현재 일반담배 흡연 여부,원본_유산소 신체활동 실천율,추출_유산소 신체활동 실천율,원본_아침식사 빈도,추출_아침식사 빈도,원본_평소 스트레스 인지 정도,추출_평소 스트레스 인지 정도,원본_혈압조절제 복용 여부,추출_혈압조절제 복용 여부,원본_당뇨병약 복용 여부,추출_당뇨병약 복용 여부,원본_이상지질혈증 약복용 여부,추출_이상지질혈증 약복용 여부,원본_당뇨병 유병여부,추출_당뇨병 유병여부,원본_고혈압 유병여부,추출_고혈압 유병여부,원본_고콜레스테롤혈증 유병여부,추출_고콜레스테롤혈증 유병여부,Sf_Score,정보손실률
0,A801223802,"### 건강검진 소견서\n\n#### 1. 신체계측 및 혈압\n수축기 혈압 133 mmHg, 이완기 혈압 76 mmHg로 경계치입니다. 체질량지수는 26.9 kg/m²로 1단계 비만이며, 허리둘레 88.8 cm로 복부비만 기준을 초과하고 있습니다.\n\n#### 2. 대사 지표\n공복혈당 102 mg/dL, 당화혈색소 5.8%로 경계치입니다. 총콜레스테롤 230 mg/dL, HDL-콜레스테롤 43 mg/dL, LDL-콜레스테롤 146 mg/dL, 중성지방 274 mg/dL로 중성지방이 높습니다.\n\n#### 3. 생활습관 및 건강행태\n1년간 체중 증가가 관찰되었습니다. 음주는 월 2~4회, 한번에 7~9잔 정도입니다. 현재는 담배를 피우지 않고 있지만 과거에는 흡연하였었습니다. 유산소 운동을 실천하지 않고 있으며, 아침식사는 주 1~2회로 적습니다. 스트레스는 조금 느끼는 편입니다.\n\n#### 4. 약물 복용 및 질환 유병 현황\n혈압약, 당뇨약, 이상지질혈증약 모두 복용하지 않습니다. 당뇨병, 고혈압 유병 여부는 확인되지 않았지만, 고콜레스테롤혈증은 정상입니다.\n\n#### 5. 종합 의견\n전반적으로 일부 경계치 수치와 생활습관 개선이 필요합니다. 체중 감소와 유산소 운동 실천, 규칙적인 식사 습관을 유지하시고, 연 1회 정기검진을 권장합니다.\n\n---\n\n[CLINICAL_DATA_RECORD]\n- 최종 수축기 혈압: 133.0 mmHg\n- 최종 이완기 혈압: 76.0 mmHg\n- 체질량지수: 26.91984854426037 kg/m²\n- 허리둘레: 88.8 cm\n- 공복혈당: 102.0 mg/dL\n- 당화혈색소: 5.8%\n- 총콜레스테롤: 230.0 mg/dL\n- HDL-콜레스테롤: 43.0 mg/dL\n- 중성지방: 274.0 mg/dL\n- LDL-콜레스테롤(직접검사): 146.0 mg/dL\n- 비만 유병여부: 1단계비만\n- 1년간 체중 변화 여부: 체중 증가\n- 1년간 음주빈도: 월 2~4회\n- 한번에 마시는 음주량: 7~9잔\n- 현재 일반담배 흡연 여부: 과거에는 피웠으나 현재 안 피움\n- 유산소 신체활동 실천율: 미실천\n- 아침식사 빈도: 주 1~2회\n- 평소 스트레스 인지 정도: 조금 느끼는 편임\n- 혈압조절제 복용 여부: 비해당\n- 당뇨병약 복용 여부: 비해당\n- 이상지질혈증 약복용 여부: 비해당\n- 당뇨병 유병여부: 결측치\n- 고혈압 유병여부: 결측치\n- 고콜레스테롤혈증 유병여부: 정상",133.0,133.0,76.0,76.0,26.919849,26.919849,88.8,88.8,102.0,102.0,5.8,5.8,230.0,230.0,43.0,43.0,274.0,274.0,146.0,146.0,1단계비만,1단계비만,체중 증가,체중 증가,월 2~4회,월 2~4회,7~9잔,7~9잔,과거에는 피웠으나 현재 안 피움,과거에는 피웠으나 현재 안 피움,미실천,미실천,주 1~2회,주 1~2회,조금 느끼는 편임,조금 느끼는 편임,비해당,비해당,비해당,비해당,비해당,비해당,결측치,결측치,결측치,결측치,정상,정상,1.0000,8.881784e-16
1,A801230601,"### 건강검진 소견서\n\n#### 1. 신체계측 및 혈압\n수축기 혈압 137 mmHg, 이완기 혈압 85 mmHg로 고혈압 경계치입니다. 체질량지수는 25.1 kg/m²로 1단계 비만이며, 허리둘레 85.3 cm로 복부비만 기준을 초과하고 있습니다.\n\n#### 2. 대사 지표\n공복혈당 96 mg/dL, 당화혈색소 5.9%로 경계값입니다. 총콜레스테롤 205 mg/dL, HDL-콜레스테롤 43 mg/dL, LDL-콜레스테롤 97 mg/dL, 중성지방 266 mg/dL로 중성지방이 높습니다.\n\n#### 3. 생활습관 및 건강행태\n1단계 비만으로, 최근 1년간 체중 변화는 없습니다. 음주는 주 2~3회 정도이며, 한번에 7~9잔을 섭취합니다. 과거에는 담배를 피웠으나 현재는 흡연하지 않고 있습니다. 유산소 운동을 실천하고 있으며, 아침식사는 주 5~7회 규칙적으로 섭취하고 있습니다. 스트레스는 조금 느끼는 편입니다.\n\n#### 4. 약물 복용 및 질환 유병 현황\n혈압조절제를 매일 복용하고 있으며, 당뇨병약과 이상지질혈증약은 복용하지 않습니다. 당뇨병, 고혈압 유병 여부는 확인되지 않았지만, 고콜레스테롤혈증은 정상입니다.\n\n#### 5. 종합 의견\n혈압과 중성지방이 높은 경계치입니다. 현재의 운동 습관과 식습관을 유지하시되, 음주량을 줄이고 체중 관리를 위해 적극적인 운동을 실천하시길 권장합니다. 연 1회 정기검진을 통해 건강 상태를 모니터링하시기 바랍니다.\n\n---\n\n**[CLINICAL_DATA_RECORD]**\n\n- 최종 수축기 혈압: 137.0 mmHg\n- 최종 이완기 혈압: 85.0 mmHg\n- 체질량지수: 25.081022062367428 kg/m²\n- 허리둘레: 85.3 cm\n- 공복혈당: 96.0 mg/dL\n- 당화혈색소: 5.9%\n- 총콜레스테롤: 205.0 mg/dL\n- HDL-콜레스테롤: 43.0 mg/dL\n- 중성지방: 266.0 mg/dL\n- LDL-콜레스테롤(직접검사): 97.0 mg/dL\n- 비만 유병여부: 1단계비만\n- 1년간 체중 변화 여부: 변화 없음\n- 1년간 음주빈도: 주 2~3회 정도\n- 한 번에 마시는 음주량: 7~9잔\n- 현재 일반담배 흡연 여부: 과거에는 피웠으나 현재 안 피움\n- 유산소 신체활동 실천율: 실천\n- 아침식사 빈도: 주 5~7회\n- 평소 스트레스 인지 정도: 조금 느끼는 편임\n- 혈압조절제 복용 여부: 매일 복용함\n- 당뇨병약 복용 여부: 비해당\n- 이상지질혈증 약복용 여부: 비해당\n- 당뇨병 유병여부: 결측치\n- 고혈압 유병여부: 결측치\n- 고콜레스테롤혈증 유병여부: 정상",137.0,137.0,85.0,85.0,25.081022,25.081022,85.3,85.3,96.0,96.0,5.9,5.9,205.0,205.0,43.0,43.0,266.0,266.0,97.0,97.0,1단계비만,1단계비만,변화 없음,변화 없음,주 2~3회 정도,주 2~3회 정도,7~9잔,7~9잔,과거에는 피웠으나 현재 안 피움,과거에는 피웠으나 현재 안 피움,실천,실천,주 5~7회,주 5~7회,조금 느끼는 편임,조금 느끼는 편임,매일 복용함,매일 복용함,비해당,비해당,비해당,비해당,결측치,결측치,결측치,결측치,정상,정상,1.0000,8.881784e-16
2,A801245901,"### 건강검진 소견서\n\n#### 1. 신체계측 및 혈압\n수축기 혈압 148 mmHg, 이완기 혈압 102 mmHg로 고혈압 범위입니다. 체질량지수는 27.0 kg/m²로 1단계 비만이며, 허리둘레 91.3 cm로 복부비만 기준 초과입니다.\n\n#### 2. 대사 지표\n공복혈당 89 mg/dL, 당화혈색소 6.0%로 정상입니다. 총콜레스테롤 203 mg/dL, HDL-콜레스테롤 40 mg/dL, LDL-콜레스테롤 95 mg/dL, 중성지방 289 mg/dL로 중성지방이 상승되어 있습니다.\n\n#### 3. 생활습관 및 건강행태\n비만 유병 1단계 비만입니다. 최근 1년간 체중 변화 없으며, 음주는 월 1회 정도입니다. 현재는 일반 담배를 피우지 않고 있으며, 유산소 운동을 주 3회 이상 실천 중입니다. 아침식사는 주 5~7회 규칙적으로 하며, 스트레스는 거의 느끼지 않는 편입니다.\n\n#### 4. 약물 복용 및 질환 유병 현황\n혈압조절제를 매일 복용하고 있으며, 당뇨병약은 복용하지 않습니다. 이상지질혈증 약도 매일 복용 중입니다. 당뇨병 유병 여부는 확인되지 않았지만, 고혈압과 고콜레스테롤혈증은 확인되었습니다.\n\n#### 5. 종합 의견\n고혈압과 1단계 비만, 중성지방 상승 등의 문제점이 있으나, 현재의 규칙적인 운동 습관과 식습관을 유지하시고, 연 1회 정기검진을 통해 건강 상태를 모니터링하시길 권장합니다.\n\n---\n\n#### [CLINICAL_DATA_RECORD]\n- 최종 수축기 혈압: 148.0 mmHg\n- 최종 이완기 혈압: 102.0 mmHg\n- 체질량지수: 26.988636363636363 kg/m²\n- 허리둘레: 91.3 cm\n- 공복혈당: 89.0 mg/dL\n- 당화혈색소: 6.0%\n- 총콜레스테롤: 203.0 mg/dL\n- HDL-콜레스테롤: 40.0 mg/dL\n- 중성지방: 289.0 mg/dL\n- LDL-콜레스테롤(직접검사): 95.0 mg/dL\n- 비만 유병여부: 1단계비만\n- 1년간 체중 변화 여부: 변화 없음\n- 1년간 음주빈도: 월 1회 정도\n- 한번에 마시는 음주량: 5~6잔\n- 현재 일반담배 흡연 여부: 과거에는 피웠으나 현재 안 피움\n- 유산소 신체활동 실천율: 실천\n- 아침식사 빈도: 주 5~7회\n- 평소 스트레스 인지 정도: 거의 느끼지 않음\n- 혈압조절제 복용 여부: 매일 복용함\n- 당뇨병약 복용 여부: 비해당\n- 이상지질혈증 약복용 여부: 매일 복용함\n- 당뇨병 유병여부: 결측치\n- 고혈압 유병여부: 결측치\n- 고콜레스테롤혈증 유병여부: 고콜레스테롤혈증",148.0,148.0,102.0,102.0,26.988636,26.988636,91.3,91.3,89.0,89.0,6.0,6.0,203.0,203.0,40.0,40.0,289.0,289.0,95.0,95.0,1단계비만,1단계비만,변화 없음,변화 없음,월 1회 정도,월 1회 정도,5~6잔,5~6잔,과거에는 피웠으나 현재 안 피움,과거에는 피웠으나 현재 안 피움,실천,실천,주 5~7회,주 5~7회,거의 느끼지 않음,거의 느끼지 않음,매일 복용함,매일 복용함,비해당,비해당,매일 복용함,매일 복용함,결측치,결측치,결측치,결측치,고콜레스테롤혈증,고콜레스테롤혈증,1.0000,8.881784e-16
3,A801249301,"### 건강검진 소견서\n\n#### 1. 신체계측 및 혈압\n수축기 혈압 129 mmHg, 이완기 혈압 91 mmHg로 고혈압 경계값에 도달하고 있습니다. 체질량지수는 26.49 kg/m²로 1단계 비만이며, 허리둘레 92.2 cm로 복부비만 기준을 초과하고 있습니다.\n\n#### 2. 대사 지표\n공복혈당 101 mg/dL, 당화혈색소 5.7%로 경계값에 도달하고 있습니다. 총콜레스테롤 207 mg/dL, HDL-콜레스테롤 41 mg/dL, LDL-콜레스테롤 113 mg/dL, 중성지방 228 mg/dL로 중성지방이 증가하여 관리 필요성이 있습니다.\n\n#### 3. 생활습관 및 건강행태\n비만 유병 1단계 비만입니다. 최근 1년간 체중 변화 없으며, 음주는 주 2~3회 정도입니다. 과거에는 담배를 피웠으나 현재는 피우지 않고 있으며, 유산소 운동을 주기적으로 실천 중입니다. 아침식사는 거의 하지 않는 편이며, 스트레스는 거의 느끼지 않는 편입니다.\n\n#### 4. 약물 복용 및 질환 유병 현황\n혈압약을 매일 복용하고 있습니다. 당뇨병약, 이상지질혈증약은 복용하지 않습니다. 당뇨병, 고혈압 유병 여부는 확인되지 않았습니다. 고콜레스테롤혈증은 정상입니다.\n\n#### 5. 종합 의견\n전반적으로 일부 항목에서 관리가 필요한 상황입니다. 현재의 운동 습관을 유지하시고, 체중 감량과 아침식사 습관을 개선하시는 것이 좋습니다. 연 1회 정기검진을 통해 건강 상태를 모니터링하시기 바랍니다.\n\n[CLINICAL_DATA_RECORD]\n- 최종 수축기 혈압: 129.0 mmHg\n- 최종 이완기 혈압: 91.0 mmHg\n- 체질량지수: 26.4917375289552 kg/m²\n- 허리둘레: 92.2 cm\n- 공복혈당: 101.0 mg/dL\n- 당화혈색소: 5.7%\n- 총콜레스테롤: 207.0 mg/dL\n- HDL-콜레스테롤: 41.0 mg/dL\n- 중성지방: 228.0 mg/dL\n- LDL-콜레스테롤(직접검사): 113.0 mg/dL\n- 비만 유병여부: 1단계비만\n- 1년간 체중 변화 여부: 변화 없음\n- 1년간 음주빈도: 주 2~3회 정도\n- 한번에 마시는 음주량: 3~4잔\n- 현재 일반담배 흡연 여부: 과거에는 피웠으나 현재 안 피움\n- 유산소 신체활동 실천율: 실천\n- 아침식사 빈도: 거의 안함\n- 평소 스트레스 인지 정도: 거의 느끼지 않음\n- 혈압조절제 복용 여부: 매일 복용함\n- 당뇨병약 복용 여부: 비해당\n- 이상지질혈증 약복용 여부: 비해당\n- 당뇨병 유병여부: 결측치\n- 고혈압 유병여부: 결측치\n- 고콜레스테롤혈증 유병여부: 정상",129.0,129.0,91.0,91.0,26.491738,26.491738,92.2,92.2,101.0,101.0,5.7,5.7,207.0,207.0,41.0,41.0,228.0,228.0,113.0,113.0,1단계비만,1단계비만,변화 없음,변화 없음,주 2~3회 정도,주 2~3회 정도,3~4잔,3~4잔,과거에는 피웠으나 현재 안 피움,과거에는 피웠으나 현재 안 피움,실천,실천,거의 안함,거의 안함,거의 느끼지 않음,거의 느끼지 않음,매일 복용함,매일 복용함,비해당,비해당,비해당,비해당,결측치,결측치,결측치,결측치,정상,정상,1.0000,8.881784e-16
4,A801364902,"### 건강검진 소견서\n\n#### 1. 신체계측 및 혈압\n수축기 혈압 177 mmHg, 이완기 혈압 106 mmHg로 고혈압 위험 범위입니다. 체질량지수는 32.2 kg/m²로 2단계 비만이며, 허리둘레 101.6 cm로 복부비만 기준을 초과하고 있습니다.\n\n#### 2. 대사 지표\n공복혈당 97 mg/dL, 당화혈색소 5.1%로 정상입니다. 총콜레스테롤 209 mg/dL, HDL-콜레스테롤 43 mg/dL, LDL-콜레스테롤 90 mg/dL, 중성지방 611 mg/dL로 중성지방이 고위험 범위입니다.\n\n#### 3. 생활습관 및 건강행태\n2단계 비만으로 1년간 체중 증가가 관찰되었습니다. 음주는 주 2~3회 정도이며, 한 번에 10잔 이상을 섭취합니다. 현재 매일 일반 담배를 피우고 있으며, 유산소 운동을 실천하고 있지만 아침식사는 주 1~2회로 불규칙합니다. 평소 스트레스를 많이 느끼고 있습니다.\n\n#### 4. 약물 복용 및 질환 유병 현황\n혈압약, 당뇨약, 이상지질혈증약 모두 복용하지 않습니다. 당뇨병 유병 없음. 고혈압 유병 여부는 확인되지 않았습니다. 고콜레스테롤혈증 유병 없음.\n\n#### 5. 종합 의견\n고혈압과 2단계 비만, 중성지방 고위험 등 여러 건강 문제를 가지고 있으므로 적극적인 생활습관 개선이 필요합니다. 체중 감소와 규칙적인 운동, 건강한 식단 유지, 금연 및 적절한 음주량 조절을 권장합니다. 정기적인 건강검진을 통해 상태를 모니터링해야 합니다.\n\n---\n\n[CLINICAL_DATA_RECORD]\n- 최종 수축기 혈압: 177.0 mmHg\n- 최종 이완기 혈압: 106.0 mmHg\n- 체질량지수: 32.22946358962339 kg/m²\n- 허리둘레: 101.6 cm\n- 공복혈당: 97.0 mg/dL\n- 당화혈색소: 5.1%\n- 총콜레스테롤: 209.0 mg/dL\n- HDL-콜레스테롤: 43.0 mg/dL\n- 중성지방: 611.0 mg/dL\n- LDL-콜레스테롤(직접검사): 90.0 mg/dL\n- 비만 유병여부: 2단계비만\n- 1년간 체중 변화 여부: 체중 증가\n- 1년간 음주빈도: 주 2~3회 정도\n- 한번에 마시는 음주량: 10잔 이상\n- 현재 일반담배 흡연 여부: 매일 피움\n- 유산소 신체활동 실천율: 실천\n- 아침식사 빈도: 주 1~2회\n- 평소 스트레스 인지 정도: 많이 느낌\n- 혈압조절제 복용 여부: 비해당\n- 당뇨병약 복용 여부: 비해당\n- 이상지질혈증 약복용 여부: 비해당\n- 당뇨병 유병여부: 정상\n- 고혈압 유병여부: 결측치\n- 고콜레스테롤혈증 유병여부: 정상",177.0,177.0,106.0,106.0,32.229464,32.229464,101.6,101.6,97.0,97.0,5.1,5.1,209.0,209.0,43.0,43.0,611.0,611.0,90.0,90.0,2단계비만,2단계비만,체중 증가,체중 증가,주 2~3회 정도,주 2~3회 정도,10잔 이상,10잔 이상,매일 피움,매일 피움,실천,실천,주 1~2회,주 1~2회,많이 느낌,많이 느낌,비해당,비해당,비해당,비해당,비해당,비해당,정상,정상,결측치,결측치,정상,정상,1.0000,8.881784e-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10053,YR62368101,"### 건강검진 소견서\n\n#### 1. 신체계측 및 혈압\n수축기 혈압 118.5 mmHg, 이완기 혈압 68.5 mmHg로 정상 범위입니다. 체질량지수는 24.0011283942828 kg/m²로 비만전단계이며, 허리둘레 97.0 cm로 복부비만 기준 초과입니다.\n\n#### 2. 대사 지표\n공복혈당 101.0 mg/dL, 당화혈색소 5.3%로 정상입니다. 총콜레스테롤 193.0 mg/dL, HDL-콜레스테롤 38.0 mg/dL, LDL-콜레스테롤 124.0 mg/dL, 중성지방 188.0 mg/dL로 HDL-콜레스테롤이 저조하고 중성지방이 상승되어 있습니다.\n\n#### 3. 생활습관 및 건강행태\n비만 전단계입니다. 최근 1년간 체중 감소가 있었습니다. 음주는 월 1회 정도이며, 한번에 1~2잔 정도 마십니다. 과거에는 담배를 피웠으나 현재는 흡연하지 않고 있습니다. 유산소 운동은 미실천 중이며, 아침식사는 주 5~7회 규칙적으로 합니다. 평소 스트레스는 조금 느끼는 편입니다.\n\n#### 4. 약물 복용 및 질환 유병 현황\n혈압조절제를 매일 복용하고 있으며, 당뇨병약도 복용 중입니다. 이상지질혈증 약은 복용하지 않습니다. 당뇨병과 고혈압이 있으며, 고콜레스테롤혈증은 정상입니다.\n\n#### 5. 종합 의견\n전반적으로 건강 상태는 양호하지만, 비만전단계와 관련된 체중 관리, HDL-콜레스테롤과 중성지방 수치 개선이 필요합니다. 유산소 운동을 실천하여 체중 관리와 심혈관 건강을 유지하시고, 정기적인 검진을 통해 건강 상태를 모니터링해주세요.\n\n---\n\n### [CLINICAL_DATA_RECORD]\n- 최종 수축기 혈압: 118.5 mmHg\n- 최종 이완기 혈압: 68.5 mmHg\n- 체질량지수: 24.0011283942828 kg/m²\n- 허리둘레: 97.0 cm\n- 공복혈당: 101.0 mg/dL\n- 당화혈색소: 5.3%\n- 총콜레스테롤: 193.0 mg/dL\n- HDL-콜레스테롤: 38.0 mg/dL\n- 중성지방: 188.0 mg/dL\n- LDL-콜레스테롤(직접검사): 124.0 mg/dL\n- 비만 유병여부: 비만전단계\n- 1년간 체중 변화 여부: 체중 감소\n- 1년간 음주빈도: 월 1회 정도\n- 한 번에 마시는 음주량: 1~2잔\n- 현재 일반담배 흡연 여부: 과거에는 피웠으나 현재 안 피움\n- 유산소 신체활동 실천율: 미실천\n- 아침식사 빈도: 주 5~7회\n- 평소 스트레스 인지 정도: 조금 느끼는 편임\n- 혈압조절제 복용 여부: 매일 복용함\n- 당뇨병약 복용 여부: 복용\n- 이상지질혈증 약복용 여부: 비해당\n- 당뇨병 유병여부: 당뇨병\n- 고혈압 유병여부: 고혈압\n- 고콜레스테롤혈증 유병여부: 정상",118.5,118.5,68.5,68.5,24.001128,24.001128,97.0,97.0,101.0,101.0,5.3,5.3,193.0,193.0,38.0,38.0,188.0,188.0,124.0,124.0,비만전단계,비만전단계,체중 감소,체중 감소,월 1회 정도,월 1회 정도,1~2잔,1~2잔,과거에는 피웠으나 현재 안 피움,과거에는 피웠으나 현재 안 피움,미실천,미실천,주 5~7회,주 5~7회,조금 느끼는 편임,조금 느끼는 편임,매일 복용함,매일 복용함,복용,복용,비해당,비해당,당뇨병,당뇨병,고혈압,고혈압,정상,정상,1.0000,8.881784e-16
10054,YR62368102,"### 건강검진 소견서\n\n#### 1. 신체계측 및 혈압\n수축기 혈압 139 mmHg, 이완기 혈압 85 mmHg로 고혈압 범위입니다. 체질량지수는 28.9775531063169 kg/m²로 1단계 비만이며, 허리둘레 97 cm로 복부비만 기준 초과입니다.\n\n#### 2. 대사 지표\n공복혈당 104 mg/dL, 당화혈색소 5.8%로 정상 범위 내입니다. 총콜레스테롤 223 mg/dL, HDL-콜레스테롤 71 mg/dL, LDL-콜레스테롤 150 mg/dL, 중성지방 110 mg/dL로 대부분 정상 범위 내이나, LDL-콜레스테롤은 상승 경향을 보입니다.\n\n#### 3. 생활습관 및 건강행태\n비만 유병 1단계 비만입니다. 최근 1년간 체중 변화 없으며, 음주는 월 1회 미만입니다. 현재 비흡연자이고 유산소 운동을 주 3회 이상 실천 중입니다. 아침식사는 주 5~7회 규칙적으로 하며, 스트레스는 조금 느끼는 편입니다.\n\n#### 4. 약물 복용 및 질환 유병 현황\n혈압약을 매일 복용하고 있습니다. 당뇨약, 이상지질혈증약은 복용하지 않습니다. 당뇨병 유병 여부는 확인되지 않았으나, 고혈압은 진단되었습니다. 고콜레스테롤혈증은 정상 범위 내입니다.\n\n#### 5. 종합 의견\n고혈압과 1단계 비만 상태를 고려하여, 적극적인 생활 습관 개선이 필요합니다. 현재의 규칙적인 운동 습관을 유지하시고, 저염식과 저지방 식사를 통해 체중 관리를 강화하시는 것이 좋습니다. 또한, 정기적인 검진을 통해 건강 상태를 모니터링하시기 바랍니다.\n\n---\n\n### CLINICAL_DATA_RECORD\n\n- 최종 수축기 혈압: 139.0 mmHg\n- 최종 이완기 혈압: 85.0 mmHg\n- 체질량지수: 28.9775531063169 kg/m²\n- 허리둘레: 97.0 cm\n- 공복혈당: 104.0 mg/dL\n- 당화혈색소: 5.8%\n- 총콜레스테롤: 223.0 mg/dL\n- HDL-콜레스테롤: 71.0 mg/dL\n- 중성지방: 110.0 mg/dL\n- LDL-콜레스테롤(직접검사): 150.0 mg/dL\n- 비만 유병여부: 1단계 비만\n- 1년간 체중 변화 여부: 변화 없음\n- 1년간 음주빈도: 월 1회 미만\n- 한번에 마시는 음주량: 1~2잔\n- 현재 일반담배 흡연 여부: 비해당\n- 유산소 신체활동 실천율: 실천\n- 아침식사 빈도: 주 5~7회\n- 평소 스트레스 인지 정도: 조금 느끼는 편임\n- 혈압조절제 복용 여부: 매일 복용함\n- 당뇨병약 복용 여부: 비해당\n- 이상지질혈증 약복용 여부: 비해당\n- 당뇨병 유병여부: 결측치\n- 고혈압 유병여부: 고혈압\n- 고콜레스테롤혈증 유병여부: 정상",139.0,139.0,85.0,85.0,28.977553,28.977553,97.0,97.0,104.0,104.0,5.8,5.8,223.0,223.0,71.0,71.0,110.0,110.0,150.0,150.0,1단계비만,1단계 비만,변화 없음,변화 없음,월 1회 미만,월 1회 미만,1~2잔,1~2잔,비해당,비해당,실천,실천,주 5~7회,주 5~7회,조금 느끼는 편임,조금 느끼는 편임,매일 복용함,매일 복용함,비해당,비해당,비해당,비해당,결측치,결측치,고혈압,고혈압,정상,정상,0.9835,1.650000e-02
10055,YR62370201,"### 건강검진 소견서\n\n#### 1. 신체계측 및 혈압\n수축기 혈압 126 mmHg, 이완기 혈압 83.5 mmHg로 정상 범위입니다. 체질량지수는 19.09 kg/m²로 정상 체중이며, 허리둘레 66.3 cm로 복부비만 기준 이하입니다.\n\n#### 2. 대사 지표\n공복혈당 90 mg/dL, 당화혈색소 5.7%로 정상입니다. 총콜레스테롤 178 mg/dL, HDL-콜레스테롤 46 mg/dL, LDL-콜레스테롤 123 mg/dL, 중성지방 91 mg/dL로 모두 정상 범위 내입니다.\n\n#### 3. 생활습관 및 건강행태\n비만 유병 없음. 최근 1년간 체중 변화 없으며, 음주는 월 1회 정도입니다. 한 번에 마시는 음주량은 1~2잔입니다. 현재 비흡연자이고 유산소 운동을 주 3회 이상 실천 중입니다. 아침식사는 주 5~7회 규칙적으로 하며, 평소 스트레스는 조금 느끼는 편입니다.\n\n#### 4. 약물 복용 및 질환 유병 현황\n혈압약, 당뇨약, 이상지질혈증약 모두 복용하지 않습니다. 당뇨병 유병 여부는 확인되지 않았으나, 고혈압 유병 여부는 확인되지 않았습니다. 고콜레스테롤혈증은 정상입니다.\n\n#### 5. 종합 의견\n전반적으로 양호한 건강 상태입니다. 현재의 규칙적인 운동 습관과 식습관을 유지하시고, 연 1회 정기검진을 권장합니다.\n\n---\n\n**CLINICAL_DATA_RECORD**\n\n- 최종 수축기 혈압: 126.0 mmHg\n- 최종 이완기 혈압: 83.5 mmHg\n- 체질량지수: 19.093749836729444 kg/m²\n- 허리둘레: 66.3 cm\n- 공복혈당: 90.0 mg/dL\n- 당화혈색소: 5.7%\n- 총콜레스테롤: 178.0 mg/dL\n- HDL-콜레스테롤: 46.0 mg/dL\n- 중성지방: 91.0 mg/dL\n- LDL-콜레스테롤(직접검사): 123.0 mg/dL\n- 비만 유병여부: 정상\n- 1년간 체중 변화 여부: 변화 없음\n- 1년간 음주빈도: 월 1회 정도\n- 한번에 마시는 음주량: 1~2잔\n- 현재 일반담배 흡연 여부: 비해당\n- 유산소 신체활동 실천율: 실천\n- 아침식사 빈도: 주 5~7회\n- 평소 스트레스 인지 정도: 조금 느끼는 편\n- 혈압조절제 복용 여부: 비해당\n- 당뇨병약 복용 여부: 비해당\n- 이상지질혈증 약복용 여부: 비해당\n- 당뇨병 유병여부: 결측치\n- 고혈압 유병여부: 결측치\n- 고콜레스테롤혈증 유병여부: 정상",126.0,126.0,83.5,83.5,19.093750,19.093750,66.3,66.3,90.0,90.0,5.7,5.7,178.0,178.0,46.0,46.0,91.0,91.0,123.0,123.0,정상,정상,변화 없음,변화 없음,월 1회 정도,월 1회 정도,1~2잔,1~2잔,비해당,비해당,실천,실천,주 5~7회,주 5~7회,조금 느끼는 편임,조금 느끼는 편,비해당,비해당,비해당,비해당,비해당,비해당,결측치,결측치,결측치,결측치,정상,정상,0.9835,1.650000e-02
10056,YR62394401,"### 건강검진 소견서\n\n#### 1. 신체계측 및 혈압\n수축기 혈압 137 mmHg, 이완기 혈압 78.5 mmHg로 수축기 혈압은 상위 정상 범위입니다. 체질량지수는 24.9 kg/m²로 비만 전 단계이며, 허리둘레 87.6 cm로 남성 기준으로 복부비만에 가깝습니다.\n\n#### 2. 대사 지표\n공복혈당 111 mg/dL로 정상 범위 상위입니다. 당화혈색소는 5.4%로 정상입니다. 총콜레스테롤 261 mg/dL로 상위 정상 범위이며, HDL-콜레스테롤 36 mg/dL, LDL-콜레스테롤 201 mg/dL, 중성지방 167 mg/dL로 모두 고콜레스테롤혈증 기준을 충족합니다.\n\n#### 3. 생활습관 및 건강행태\n비만 전 단계입니다. 최근 1년간 체중 변화 없으며, 음주는 월 1회 정도입니다. 한 번에 마시는 음주량은 7~9잔입니다. 현재 비흡연자이고 유산소 운동을 주 3회 이상 실천 중입니다. 아침식사는 주 5~7회 규칙적으로 하며, 스트레스는 조금 느끼는 편입니다.\n\n#### 4. 약물 복용 및 질환 유병 현황\n혈압약, 당뇨약, 이상지질혈증약 모두 복용하지 않습니다. 당뇨병 유병 여부는 확인되지 않았으며, 고혈압 유병 여부도 확인되지 않았습니다. 고콜레스테롤혈증은 확인되었습니다.\n\n#### 5. 종합 의견\n전반적으로 건강 상태는 양호하지만, 수축기 혈압과 총콜레스테롤, LDL-콜레스테롤, 중성지방 등이 상위 정상 범위 또는 고콜레스테롤혈증 기준을 충족하고 있습니다. 현재의 규칙적인 운동 습관과 식습관을 유지하시고, 연 1회 정기검진을 통해 건강 상태를 모니터링하는 것이 필요합니다.\n\n---\n\n#### CLINICAL_DATA_RECORD\n\n- 최종 수축기 혈압: 137.0 mmHg\n- 최종 이완기 혈압: 78.5 mmHg\n- 체질량지수: 24.91640946502057 kg/m²\n- 허리둘레: 87.6 cm\n- 공복혈당: 111.0 mg/dL\n- 당화혈색소: 5.4%\n- 총콜레스테롤: 261.0 mg/dL\n- HDL-콜레스테롤: 36.0 mg/dL\n- 중성지방: 167.0 mg/dL\n- LDL-콜레스테롤(직접검사): 201.0 mg/dL\n- 비만 유병여부: 비만전단계\n- 1년간 체중 변화 여부: 변화 없음\n- 1년간 음주빈도: 월 1회 정도\n- 한번에 마시는 음주량: 7~9잔\n- 현재 일반담배 흡연 여부: 비해당\n- 유산소 신체활동 실천율: 실천\n- 아침식사 빈도: 주 5~7회\n- 평소 스트레스 인지 정도: 조금 느끼는 편임\n- 혈압조절제 복용 여부: 비해당\n- 당뇨병약 복용 여부: 비해당\n- 이상지질혈증 약복용 여부: 비해당\n- 당뇨병 유병여부: 결측치\n- 고혈압 유병여부: 결측치\n- 고콜레스테롤혈증 유병여부: 고콜레스테롤혈증",137.0,137.0,78.5,78.5,24.916409,24.916409,87.6,87.6,111.0,111.0,5.4,5.4,261.0,261.0,36.0,36.0,167.0,167.0,201.0,201.0,비만전단계,비만전단계,변화 없음,변화 없음,월 1회 정도,월 1회 정도,7~9잔,7~9잔,비해당,비해당,실천,실천,주 5~7회,주 5~7회,조금 느끼는 편임,조금 느끼는 편임,비해당,비해당,비해당,비해당,비해당,비해당,결측치,결측치,결측치,결측치,고콜레스테롤혈증,고콜레스테롤혈증,1.0000,8.881784e-16
10057,YR62432901,"### 건강검진 소견서\n\n#### 1. 신체계측 및 혈압\n수축기 혈압 126.5 mmHg, 이완기 혈압 85.5 mmHg로 정상 범위입니다. 체질량지수는 20.26 kg/m²로 정상 체중이며, 허리둘레 75.7 cm로 복부비만 기준 이하입니다.\n\n#### 2. 대사 지표\n공복혈당 87.0 mg/dL, 당화혈색소 5.4%로 정상입니다. 총콜레스테롤 209.0 mg/dL, HDL-콜레스테롤 60.0 mg/dL, LDL-콜레스테롤 98.0 mg/dL, 중성지방 443.0 mg/dL로 중성지방은 상승 경향을 보입니다.\n\n#### 3. 생활습관 및 건강행태\n비만 유병 없음. 최근 1년간 체중 감소가 있었습니다. 음주는 주 4회 정도이며, 한번에 10잔 이상을 마십니다. 현재 일반담배를 매일 피우고 있으며, 유산소 운동을 실천하지 않고 있습니다. 아침식사는 거의 먹지 않으며, 평소 스트레스는 조금 느끼는 편입니다.\n\n#### 4. 약물 복용 및 질환 유병 현황\n혈압약, 당뇨약, 이상지질혈증약 모두 복용하지 않습니다. 당뇨병 유병 없음. 고혈압 유병 여부는 확인되지 않았습니다. 고콜레스테롤혈증 유병 없음.\n\n#### 5. 종합 의견\n전반적으로 건강 상태는 양호하지만, 중성지방 수치가 상승하고 있습니다. 또한, 체중 감소, 과도한 음주, 담배 흡연, 유산소 운동 미실천 등 여러 생활습관 개선이 필요합니다. 아침식사를 규칙적으로 섭취하고, 적정량의 음주와 담배 흡연을 줄이는 것이 좋습니다. 연 1회 정기검진을 통해 건강 상태를 모니터링해주시기 바랍니다.\n\n---\n\n### CLINICAL_DATA_RECORD\n- 수축기 혈압: 126.5 mmHg\n- 이완기 혈압: 85.5 mmHg\n- 체질량지수: 20.259727145573805 kg/m²\n- 허리둘레: 75.7 cm\n- 공복혈당: 87.0 mg/dL\n- 당화혈색소: 5.4%\n- 총콜레스테롤: 209.0 mg/dL\n- HDL-콜레스테롤: 60.0 mg/dL\n- LDL-콜레스테롤(직접검사): 98.0 mg/dL\n- 중성지방: 443.0 mg/dL\n- 비만 유병여부: 정상\n- 1년간 체중 변화 여부: 체중 감소\n- 1년간 음주빈도: 주 4회 정도\n- 한번에 마시는 음주량: 10잔 이상\n- 현재 일반담배 흡연 여부: 매일 피움\n- 유산소 신체활동 실천율: 미실천\n- 아침식사 빈도: 거의 안함\n- 평소 스트레스 인지 정도: 조금 느끼는 편임\n- 혈압조절제 복용 여부: 비해당\n- 당뇨병약 복용 여부: 비해당\n- 이상지질혈증 약복용 여부: 비해당\n- 당뇨병 유병여부: 정상\n- 고혈압 유병여부: 결측치\n- 고콜레스테롤혈증 유병여부: 정상",126.5,126.5,85.5,85.5,20.259727,20.259727,75.7,75.7,87.0,87.0,5.4,5.4,209.0,209.0,60.0,60.0,443.0,443.0,98.0,98.0,정상,정상,체중 감소,체중 감소,주 4회 정도,주 4회 정도,10잔 이상,10잔 이상,매일 피움,매일 피움,미실천,미실천,거의 안함,거의 안함,조금 느끼는 편임,조금 느끼는 편임,비해당,비해당,비해당,비해당,비해당,비해당,정상,정상,결측치,결측치,정상,정상,1.0000,8.881784e-16

## 4. (4단계)정보 손실률($1 - S_f$) 높은 사례 분석 및 환각 유형 분류

# (1저자 수행 예정)

In [14]:
all_vars = [col.replace('원본_', '') for col in df_final_audit.columns if col.startswith('원본_')]

In [16]:
import pandas as pd

# Phase 3에서 정의된 all_vars (24개 변수)를 그대로 사용합니다.
print(f"🔎 분석 대상 변수: 총 {len(all_vars)}개 지표")

def analyze_24var_hallucination(df, var_list):
    # 1. 정보 손실이 발생한 레코드 필터링 (Sf < 1.0)
    error_df = df[df['Sf_Score'] < 1.0].copy()
    
    if len(error_df) == 0:
        print("✅ [감사 결과] 모든 레코드의 Sf_Score가 1.0입니다. 환각 사례가 발견되지 않았습니다.")
        return None

    results = []
    print(f"⚠️ 총 {len(error_df)}건에서 미세 오차 또는 환각 의심 사례 포착. 상세 분석 중...")

    for _, row in error_df.iterrows():
        mismatches = []
        
        for var in var_list:
            orig = row[f'원본_{var}']
            recon = row[f'추출_{var}']
            
            # 수치형/범주형 범용 비교 (데이터 타입에 따른 유연한 처리)
            if orig != recon:
                # 오차 크기 계산 (수치형일 경우만)
                try:
                    diff = abs(float(orig) - float(recon))
                    mismatches.append(f"[{var}] 원본:{orig} -> 추출:{recon} (오차:{diff})")
                except:
                    # 범주형(텍스트)일 경우
                    mismatches.append(f"[{var}] 원본:{orig} -> 추출:{recon} (불일치)")
        
        results.append({
            '개인아이디': row['개인아이디'],
            '최종_Sf_Score': row['Sf_Score'],
            '정보손실률': row['정보손실률'],
            '상세_오류_내용': " | ".join(mismatches),
            '소견서_샘플': row['합성_소견서']
        })

    return pd.DataFrame(results)

# --- 실행 ---
df_hallucination_report = analyze_24var_hallucination(df_final_audit, all_vars)

if df_hallucination_report is not None:
    display(df_hallucination_report[['개인아이디', '정보손실률', '상세_오류_내용']])
    df_hallucination_report.to_csv("hallucination_audit_report.csv", index=False, encoding='utf-8-sig')

🔎 분석 대상 변수: 총 24개 지표
⚠️ 총 1018건에서 미세 오차 또는 환각 의심 사례 포착. 상세 분석 중...

,개인아이디,정보손실률,상세_오류_내용
0,A802279901,0.016000,[고콜레스테롤혈증 유병여부] 원본:정상 -> 추출:nan (불일치)
1,A804222101,0.002963,[LDL-콜레스테롤(직접검사)] 원본:108.0 -> 추출:128.0 (오차:20.0)
2,A804310502,0.016000,[LDL-콜레스테롤(직접검사)] 원본:105.0 -> 추출:1105.0 (오차:1000.0)
3,A804339402,0.015863,[LDL-콜레스테롤(직접검사)] 원본:117.0 -> 추출:1.0 (오차:116.0)
4,A809283301,0.015840,[LDL-콜레스테롤(직접검사)] 원본:100.0 -> 추출:1.0 (오차:99.0)
...,...,...,...
1013,YR90370202,0.015857,[LDL-콜레스테롤(직접검사)] 원본:112.0 -> 추출:1.0 (오차:111.0)
1014,YR90384302,0.000147,[LDL-콜레스테롤(직접검사)] 원본:109.0 -> 추출:110.0 (오차:1.0)
1015,YR90390402,0.015902,[LDL-콜레스테롤(직접검사)] 원본:164.0 -> 추출:1.0 (오차:163.0)
1016,YR62277102,0.144328,[체질량지수] 원본:25.6495033710776 -> 추출:25.6 (오차:0.0495033710775985) | [현재 일반담배 흡연 여부] 원본:비해당 -> 추출:비흡연자 (불일치) | [유산소 신체활동 실천율] 원본:미실천 -> 추출:미실천중 (불일치) | [평소 스트레스 인지 정도] 원본:조금느끼는편임 -> 추출:조금느끼는편 (불일치) | [혈압조절제 복용 여부] 원본:매일복용함 -> 추출:매일복용중 (불일치) | [당뇨병약 복용 여부] 원본:비해당 -> 추출:복용하지않음 (불일치) | [이상지질혈증 약복용 여부] 원본:매일복용함 -> 추출:매일복용중 (불일치) | [당뇨병 유병여부] 원본:정상 -> 추출:유병없음 (불일치) | [고혈압 유병여부] 원본:고혈압 -> 추출:유병있음 (불일치) | [고콜레스테롤혈증 유병여부] 원본:고콜레스테롤혈증 -> 추출:유병있음 (불일치)
1017,YR62370201,0.016000,[평소 스트레스 인지 정도] 원본:조금느끼는편임 -> 추출:조금느끼는편 (불일치)

#### 'hallucination_audit_report.csv' 파일 토대로 환각 분석 리포트 작성 (1저자)

In [17]:
"""
환각분석 리포트 데이터 추출 코드
──────────────────────────────
hallucination_audit_report.csv를 입력으로,
리포트의 모든 표(Table)에 해당하는 수치를 산출함.

필요 파일: hallucination_audit_report.csv (소견서 전문 포함 버전)
"""

import pandas as pd
import numpy as np
import re
import unicodedata
from collections import Counter
import warnings
warnings.filterwarnings('ignore')

# =============================================================================
# 0. 데이터 로드
# =============================================================================
df = pd.read_csv("hallucination_audit_report.csv")
df_err = df[df['상세_오류_내용'].notna()].copy()

# =============================================================================
# 1. 변수 분류 및 임상적 허용 범위
# =============================================================================
cont_vars = [
    '최종 수축기 혈압', '최종 이완기 혈압', '체질량지수', '허리둘레',
    '공복혈당', '당화혈색소', '총콜레스테롤', 'HDL-콜레스테롤',
    '중성지방', 'LDL-콜레스테롤(직접검사)'
]

cat_vars = [
    '비만 유병여부', '1년간 체중 변화 여부', '1년간 음주빈도', '한번에 마시는 음주량',
    '현재 일반담배 흡연 여부', '유산소 신체활동 실천율', '아침식사 빈도',
    '평소 스트레스 인지 정도', '혈압조절제 복용 여부', '당뇨병약 복용 여부',
    '이상지질혈증 약복용 여부', '당뇨병 유병여부', '고혈압 유병여부', '고콜레스테롤혈증 유병여부'
]

CLINICAL_TOLERANCE = {
    '최종 수축기 혈압': 5.0, '최종 이완기 혈압': 5.0,
    '체질량지수': 0.5, '허리둘레': 1.0,
    '공복혈당': 5.0, '당화혈색소': 0.2,
    '총콜레스테롤': 5.0, 'HDL-콜레스테롤': 3.0,
    '중성지방': 5.0, 'LDL-콜레스테롤(직접검사)': 5.0,
}

# =============================================================================
# 2. 범주형 정규화 함수
# =============================================================================
def normalize_cat(text):
    s = str(text).strip()
    if s.lower() in ('nan', 'none', '', 'null'):
        return 'nan'
    s = unicodedata.normalize('NFC', s)
    s = s.replace('~', '-')
    s = re.sub(r'\.\s*$', '', s)
    s = s.replace(' ', '')
    return s

# =============================================================================
# 3. 오류 파싱
# =============================================================================
def parse_errors(error_str):
    if pd.isna(error_str):
        return []
    errors = []
    for item in error_str.split(" | "):
        m = re.match(r'\[(.+?)\]\s*원본:(.+?)\s*->\s*추출:(.+?)\s*\((.+?)\)', item.strip())
        if not m:
            continue
        var, orig, recon, info = m.group(1).strip(), m.group(2).strip(), m.group(3).strip(), m.group(4).strip()
        entry = {'var': var, 'orig': orig, 'recon': recon, 'is_nan': False, 'is_numeric': False, 'diff': None}

        if recon.lower() == 'nan':
            entry['is_nan'] = True
        elif info == '불일치':
            pass
        elif info.startswith('오차:'):
            raw = info.replace('오차:', '')
            if raw.lower() == 'nan':
                entry['is_nan'] = True
            else:
                try:
                    entry['diff'] = float(raw)
                    entry['is_numeric'] = True
                except ValueError:
                    pass
        errors.append(entry)
    return errors

# =============================================================================
# 4. 환각 유형 분류
# =============================================================================
def classify_hallucination(entry):
    if entry['is_nan']:
        return 'Extraction Failure'
    if entry['is_numeric'] and entry['var'] in cont_vars:
        tol = CLINICAL_TOLERANCE.get(entry['var'], 5.0)
        if entry['diff'] is not None and entry['diff'] > tol:
            return 'Fatal Hallucination'
        else:
            return 'Numerical Distortion'
    o, r = normalize_cat(entry['orig']), normalize_cat(entry['recon'])
    if o == r:
        return 'Surface Variation'
    return 'Categorical Mutation'

# =============================================================================
# 5. 소견서 내 원본값 존재 여부 (오류 귀인)
# =============================================================================
def check_in_text(text, var, orig, is_numeric):
    if pd.isna(text):
        return False
    text = str(text)
    if is_numeric:
        try:
            num = float(orig)
            if num == int(num):
                if str(int(num)) in text or f"{num:.1f}" in text:
                    return True
            else:
                for fmt in [str(num), f"{num:.1f}", f"{num:.2f}", orig]:
                    if fmt in text:
                        return True
            if str(int(num)) in text:
                return True
            return False
        except:
            return False
    else:
        return normalize_cat(orig) in text.replace(' ', '')

# =============================================================================
# 6. 전체 분류 실행
# =============================================================================
all_errors = []
row_summaries = []

for _, row in df_err.iterrows():
    parsed = parse_errors(row['상세_오류_내용'])
    tc = Counter()
    fatal_vars, fail_vars = [], []

    for entry in parsed:
        h_type = classify_hallucination(entry)
        tc[h_type] += 1

        # 오류 귀인
        if entry['is_nan']:
            source = 'Extraction Failure'
        elif check_in_text(row['소견서_샘플'], entry['var'], entry['orig'], entry['is_numeric']):
            source = 'Extraction Error'
        else:
            source = 'Synthesis Error'

        all_errors.append({
            '개인아이디': row['개인아이디'], '정보손실률': row['정보손실률'],
            '변수명': entry['var'], '원본값': entry['orig'], '추출값': entry['recon'],
            '오차': entry['diff'], '수치형': entry['is_numeric'],
            '환각유형': h_type, '오류원인': source,
        })
        if h_type == 'Fatal Hallucination': fatal_vars.append(entry['var'])
        if h_type == 'Extraction Failure': fail_vars.append(entry['var'])

    total_err = sum(tc.values())
    if tc.get('Extraction Failure', 0) > 0 and tc['Extraction Failure'] == total_err:
        severity = 'Total Failure'
    elif tc.get('Extraction Failure', 0) > 0 or tc.get('Fatal Hallucination', 0) > 0:
        severity = 'Critical'
    elif tc.get('Categorical Mutation', 0) > 0:
        severity = 'Major'
    elif tc.get('Numerical Distortion', 0) > 0:
        severity = 'Minor'
    else:
        severity = 'Trivial'

    row_summaries.append({
        '개인아이디': row['개인아이디'], '정보손실률': row['정보손실률'],
        '최종_Sf_Score': row['최종_Sf_Score'], '총_오류수': len(parsed),
        'Extraction_Failure': tc.get('Extraction Failure', 0),
        'Fatal_Hallucination': tc.get('Fatal Hallucination', 0),
        'Categorical_Mutation': tc.get('Categorical Mutation', 0),
        'Numerical_Distortion': tc.get('Numerical Distortion', 0),
        'Surface_Variation': tc.get('Surface Variation', 0),
        '최고_심각도': severity,
        'Fatal_변수': ', '.join(fatal_vars) if fatal_vars else '-',
    })

df_errors = pd.DataFrame(all_errors)
df_summary = pd.DataFrame(row_summaries)

# =============================================================================
# 7. 리포트 출력
# =============================================================================
sf = df['최종_Sf_Score']

print("=" * 80)
print(" LLM 합성 소견서 환각(Hallucination) 분석 리포트")
print("=" * 80)

# ── 1. 전체 현황 ──
print("\n" + "=" * 80)
print("[1] 전체 데이터 정합성 현황")
print("=" * 80)
n_total = len(df)
n_clean = n_total - len(df_err)
print(f"  전체 레코드:        {n_total:>6d}건  (100.0%)")
print(f"  완전 정합 (Sf=1.0): {n_clean:>6d}건  ({n_clean/n_total*100:.1f}%)")
print(f"  오류 발생 (Sf<1.0): {len(df_err):>6d}건  ({len(df_err)/n_total*100:.1f}%)  → 개별 오류 {len(df_errors)}건")

# ── 1.1 Sf 기초통계량 ──
print("\n[1.1] Sf Score 기초통계량")
print(f"  {'구분':20s} {'Mean':>8s} {'SD':>8s} {'Min':>8s} {'Median':>8s} {'Max':>8s}")
print(f"  {'전체 (N='+str(n_total)+')':20s} {sf.mean():>8.4f} {sf.std():>8.4f} {sf.min():>8.4f} {sf.median():>8.4f} {sf.max():>8.4f}")
sf_err = df_err['최종_Sf_Score']
print(f"  {'오류 (N='+str(len(df_err))+')':20s} {sf_err.mean():>8.4f} {sf_err.std():>8.4f} {sf_err.min():>8.4f} {sf_err.median():>8.4f} {sf_err.max():>8.4f}")

# ── 1.2 구간별 분포 ──
print("\n[1.2] Sf Score 구간별 분포")
bins_def = [
    (1.0 - 1e-10, 1.001, '1.0 (완전 정합)'),
    (0.999, 1.0 - 1e-10, '0.999 ~ <1.0'),
    (0.99, 0.999, '0.99 ~ 0.999'),
    (0.95, 0.99, '0.95 ~ 0.99'),
    (0.9, 0.95, '0.9 ~ 0.95'),
    (0.8, 0.9, '0.8 ~ 0.9'),
    (0.5, 0.8, '0.5 ~ 0.8'),
    (0, 0.5, '0 ~ 0.5'),
]
cumul = 0
print(f"  {'Sf 구간':20s} {'건수':>7s} {'비율(%)':>8s} {'누적(%)':>8s}")
for lo, hi, label in bins_def:
    cnt = ((sf >= lo) & (sf < hi)).sum()
    cumul += cnt
    print(f"  {label:20s} {cnt:>7d} {cnt/n_total*100:>8.1f} {cumul/n_total*100:>8.1f}")

# ── 1.3 백분위수 ──
print("\n[1.3] Sf Score 백분위수")
pcts = [1, 5, 10, 25, 50, 75, 90, 95, 99]
vals = [f"{sf.quantile(q/100):.4f}" for q in pcts]
print(f"  {'백분위':>8s}: " + "  ".join([f"P{q}" for q in pcts]))
print(f"  {'Sf Score':>8s}: " + "  ".join(vals))

# ── 2. 환각 유형 분류 ──
print("\n\n" + "=" * 80)
print("[2] 환각 유형별 발생 빈도 (N = {})".format(len(df_errors)))
print("=" * 80)
type_order = ['Fatal Hallucination', 'Extraction Failure', 'Categorical Mutation',
              'Surface Variation', 'Numerical Distortion']
type_counts = df_errors['환각유형'].value_counts()
total_err = len(df_errors)
for t in type_order:
    cnt = type_counts.get(t, 0)
    print(f"  {t:30s}: {cnt:>6d}건 ({cnt/total_err*100:>6.2f}%)")
print(f"  {'합계':30s}: {total_err:>6d}건")

# ── 2.1 변수별 크로스탭 ──
print("\n[2.1] 변수별 환각 유형 분포")
cross = pd.crosstab(df_errors['변수명'], df_errors['환각유형'])
for t in type_order:
    if t not in cross.columns:
        cross[t] = 0
cross = cross[type_order]
cross['합계'] = cross.sum(axis=1)
cross = cross.sort_values('합계', ascending=False)
print(cross.to_string())

# ── 3. Fatal Hallucination 상세 ──
print("\n\n" + "=" * 80)
print("[3] 치명적 환각(Fatal Hallucination) 변수별 오차 통계")
print("=" * 80)
fatal_df = df_errors[df_errors['환각유형'] == 'Fatal Hallucination'].copy()
if len(fatal_df) > 0:
    fatal_df['오차'] = pd.to_numeric(fatal_df['오차'], errors='coerce')
    fatal_stats = fatal_df.groupby('변수명')['오차'].agg(
        건수='count', 평균오차='mean', 중앙값='median', 최대오차='max'
    ).round(2).sort_values('건수', ascending=False)
    # Tolerance 추가
    fatal_stats['Tolerance'] = fatal_stats.index.map(CLINICAL_TOLERANCE)
    print(fatal_stats.to_string())

# ── 4. 레코드 심각도 ──
print("\n\n" + "=" * 80)
print("[4] 레코드 심각도 등급 분포 (오류 레코드 N = {})".format(len(df_summary)))
print("=" * 80)
sev_order = ['Total Failure', 'Critical', 'Major', 'Minor', 'Trivial']
sev_counts = df_summary['최고_심각도'].value_counts()
for s in sev_order:
    cnt = sev_counts.get(s, 0)
    print(f"  {s:15s}: {cnt:>6d}건 ({cnt/len(df_summary)*100:>6.2f}%)")

# ── 5. 합성-추출 오류 귀인 ──
print("\n\n" + "=" * 80)
print("[5] 합성-추출 단계별 오류 귀인 분석 (N = {})".format(len(df_errors)))
print("=" * 80)

# 5.1 종합
src_counts = df_errors['오류원인'].value_counts()
src_order = ['Extraction Error', 'Extraction Failure', 'Synthesis Error']
for s in src_order:
    cnt = src_counts.get(s, 0)
    print(f"  {s:25s}: {cnt:>6d}건 ({cnt/total_err*100:>5.1f}%)")
n_ext = src_counts.get('Extraction Error', 0) + src_counts.get('Extraction Failure', 0)
n_syn = src_counts.get('Synthesis Error', 0)
print(f"\n  추출 단계 귀인 소계:     {n_ext:>6d}건 ({n_ext/total_err*100:.1f}%)")
print(f"  합성 단계 귀인 소계:     {n_syn:>6d}건 ({n_syn/total_err*100:.1f}%)")

# 5.2 변수 척도별
print("\n[5.2] 변수 척도별 오류 원인 분포")
num_mask = df_errors['수치형'] == True
for label, mask in [("연속형", num_mask), ("범주형", ~num_mask)]:
    sub = df_errors[mask]
    sub_src = sub['오류원인'].value_counts()
    n = len(sub)
    parts = []
    for s in src_order:
        c = sub_src.get(s, 0)
        parts.append(f"{s}={c}({c/n*100:.1f}%)" if n > 0 else f"{s}=0")
    print(f"  {label} (N={n}): " + ", ".join(parts))

# 5.3 연속형 변수별 상세
print("\n[5.3] 연속형 변수별 오류 원인 상세")
num_errors = df_errors[num_mask]
if len(num_errors) > 0:
    num_cross = pd.crosstab(num_errors['변수명'], num_errors['오류원인'])
    for s in src_order:
        if s not in num_cross.columns:
            num_cross[s] = 0
    num_cross = num_cross[src_order]
    num_cross['합계'] = num_cross.sum(axis=1)
    num_cross = num_cross.sort_values('합계', ascending=False)
    print(num_cross.to_string())

# 5.4 Synthesis Error 상세
print("\n[5.4] Synthesis Error 상세 (상위 20건)")
synth = df_errors[df_errors['오류원인'] == 'Synthesis Error']
if len(synth) > 0:
    print(f"  총 {len(synth)}건")
    print(synth[['변수명', '원본값', '추출값']].head(20).to_string(index=False))

# ── 6. 종합 요약 ──
print("\n\n" + "=" * 80)
print("[6] 종합 요약")
print("=" * 80)
n_trivial = sev_counts.get('Trivial', 0)
n_minor = sev_counts.get('Minor', 0)
n_major = sev_counts.get('Major', 0)
n_critical = sev_counts.get('Critical', 0) + sev_counts.get('Total Failure', 0)
print(f"  완전 정합 (Sf=1.0):        {n_clean:>6d}건 ({n_clean/n_total*100:.1f}%)")
print(f"  Surface Variation (Trivial):{n_trivial:>5d}건 ({n_trivial/n_total*100:.1f}%)")
print(f"  Numerical Distortion (Minor):{n_minor:>4d}건 ({n_minor/n_total*100:.1f}%)")
print(f"  Categorical Mutation (Major):{n_major:>4d}건 ({n_major/n_total*100:.1f}%)")
print(f"  Critical (심각/실패):       {n_critical:>5d}건 ({n_critical/n_total*100:.1f}%)")
print(f"\n  실질적 무결성 (정합+Trivial): {n_clean+n_trivial}건 ({(n_clean+n_trivial)/n_total*100:.1f}%)")

# =============================================================================
# 8. CSV 저장
# =============================================================================
df_errors.to_csv("hallucination_error_detail.csv", index=False, encoding='utf-8-sig')
df_summary.to_csv("hallucination_record_summary.csv", index=False, encoding='utf-8-sig')
print("\n\n저장 완료:")
print("  - hallucination_error_detail.csv  (개별 오류 단위, 환각유형 + 오류원인 포함)")
print("  - hallucination_record_summary.csv (레코드 단위 요약)")

================================================================================
 LLM 합성 소견서 환각(Hallucination) 분석 리포트
================================================================================

================================================================================
[1] 전체 데이터 정합성 현황
================================================================================
  전체 레코드:          1018건  (100.0%)
  완전 정합 (Sf=1.0):      0건  (0.0%)
  오류 발생 (Sf<1.0):   1018건  (100.0%)  → 개별 오류 2009건

[1.1] Sf Score 기초통계량
  구분                       Mean       SD      Min   Median      Max
  전체 (N=1018)            0.9599   0.1117   0.0000   0.9841   1.0000
  오류 (N=1018)            0.9599   0.1117   0.0000   0.9841   1.0000

[1.2] Sf Score 구간별 분포
  Sf 구간                     건수    비율(%)    누적(%)
  1.0 (완전 정합)                1      0.1      0.1
  0.999 ~ <1.0              24      2.4      2.5
  0.99 ~ 0.999             145     14.2     16.7
  0.95 ~ 0.99              729     71.6     88.3
  0.9 ~ 0.95                 8      0.8     89.1
  0.8 ~ 0.9                 89      8.7     97.8
  0.5 ~ 0.8                 11      1.1     98.9
  0 ~ 0.5                   11      1.1    100.0

[1.3] Sf Score 백분위수
       백분위: P1  P5  P10  P25  P50  P75  P90  P95  P99
  Sf Score: 0.0897  0.8316  0.8810  0.9840  0.9841  0.9842  0.9981  0.9985  1.0000


================================================================================
[2] 환각 유형별 발생 빈도 (N = 2009)
================================================================================
  Fatal Hallucination           :    716건 ( 35.64%)
  Extraction Failure            :    519건 ( 25.83%)
  Categorical Mutation          :    695건 ( 34.59%)
  Surface Variation             :      6건 (  0.30%)
  Numerical Distortion          :     73건 (  3.63%)
  합계                            :   2009건

[2.1] 변수별 환각 유형 분포
환각유형             Fatal Hallucination  Extraction Failure  Categorical Mutation  Surface Variation  Numerical Distortion   합계
변수명
LDL-콜레스테롤(직접검사)                  499                  16                     0                  0                     4  519
평소 스트레스 인지 정도                      0                  28                   118                  0                     0  146
아침식사 빈도                            0                 130                    13                  0                     0  143
중성지방                              98                  13                     0                  0                     2  113
이상지질혈증 약복용 여부                      0                  24                    69                  0                     0   93
당뇨병약 복용 여부                         0                  17                    74                  0                     0   91
혈압조절제 복용 여부                        0                  18                    71                  0                     0   89
현재 일반담배 흡연 여부                      0                  21                    68                  0                     0   89
체질량지수                              0                  11                     0                  0                    66   77
고혈압 유병여부                           0                  19                    49                  5                     0   73
공복혈당                              56                  11                     0                  0                     1   68
유산소 신체활동 실천율                       0                  19                    48                  0                     0   67
당뇨병 유병여부                           0                  18                    47                  1                     0   66
고콜레스테롤혈증 유병여부                      0                  21                    41                  0                     0   62
1년간 음주빈도                           0                  18                    39                  0                     0   57
한번에 마시는 음주량                        0                  26                    24                  0                     0   50
HDL-콜레스테롤                         29                  15                     0                  0                     0   44
1년간 체중 변화 여부                       0                  16                    22                  0                     0   38
총콜레스테롤                            21                  13                     0                  0                     0   34
비만 유병여부                            0                  16                    12                  0                     0   28
허리둘레                               9                  11                     0                  0                     0   20
당화혈색소                              3                  16                     0                  0                     0   19
최종 이완기 혈압                          1                  11                     0                  0                     0   12
최종 수축기 혈압                          0                  11                     0                  0                     0   11


================================================================================
[3] 치명적 환각(Fatal Hallucination) 변수별 오차 통계
================================================================================
                  건수    평균오차    중앙값     최대오차  Tolerance
변수명
LDL-콜레스테롤(직접검사)  499  301.02  105.0  12000.0        5.0
중성지방              98  531.44  166.0  10000.0        5.0
공복혈당              56  225.64  101.0   1000.0        5.0
HDL-콜레스테롤         29   98.79   99.0    215.0        3.0
총콜레스테롤            21  459.33  195.0   1000.0        5.0
허리둘레               9  381.41  102.4   1000.0        1.0
당화혈색소              3   69.12  100.0    102.2        0.2
최종 이완기 혈압          1   42.00   42.0     42.0        5.0


================================================================================
[4] 레코드 심각도 등급 분포 (오류 레코드 N = 1018)
================================================================================
  Total Failure  :    150건 ( 14.73%)
  Critical       :    722건 ( 70.92%)
  Major          :    117건 ( 11.49%)
  Minor          :     23건 (  2.26%)
  Trivial        :      6건 (  0.59%)


================================================================================
[5] 합성-추출 단계별 오류 귀인 분석 (N = 2009)
================================================================================
  Extraction Error         :   1011건 ( 50.3%)
  Extraction Failure       :    519건 ( 25.8%)
  Synthesis Error          :    479건 ( 23.8%)

  추출 단계 귀인 소계:       1530건 (76.2%)
  합성 단계 귀인 소계:        479건 (23.8%)

[5.2] 변수 척도별 오류 원인 분포
  연속형 (N=789): Extraction Error=789(100.0%), Extraction Failure=0(0.0%), Synthesis Error=0(0.0%)
  범주형 (N=1220): Extraction Error=222(18.2%), Extraction Failure=519(42.5%), Synthesis Error=479(39.3%)

[5.3] 연속형 변수별 오류 원인 상세
오류원인             Extraction Error  Extraction Failure  Synthesis Error   합계
변수명
LDL-콜레스테롤(직접검사)               503                   0                0  503
중성지방                          100                   0                0  100
체질량지수                          66                   0                0   66
공복혈당                           57                   0                0   57
HDL-콜레스테롤                      29                   0                0   29
총콜레스테롤                         21                   0                0   21
허리둘레                            9                   0                0    9
당화혈색소                           3                   0                0    3
최종 이완기 혈압                       1                   0                0    1

[5.4] Synthesis Error 상세 (상위 20건)
  총 479건
          변수명     원본값      추출값
현재 일반담배 흡연 여부     비해당     비흡연자
평소 스트레스 인지 정도 대단히많이느낌    대단히많음
  혈압조절제 복용 여부     비해당   복용하지않음
   당뇨병약 복용 여부     비해당   복용하지않음
     당뇨병 유병여부     결측치   확인되지않음
     1년간 음주빈도 주2-3회정도    주2-3회
현재 일반담배 흡연 여부    매일피움       매일
평소 스트레스 인지 정도 조금느끼는편임       조금
  혈압조절제 복용 여부     비해당   복용하지않음
   당뇨병약 복용 여부     비해당   복용하지않음
이상지질혈증 약복용 여부     비해당   복용하지않음
     고혈압 유병여부     결측치   확인되지않음
     1년간 음주빈도     비해당   해당사항없음
  한번에 마시는 음주량     비해당   해당사항없음
현재 일반담배 흡연 여부     비해당     비흡연자
      아침식사 빈도    거의안함 거의섭취하지않음
평소 스트레스 인지 정도    많이느낌   많이느끼는편
  혈압조절제 복용 여부     비해당   복용하지않음
   당뇨병약 복용 여부     비해당   복용하지않음
이상지질혈증 약복용 여부   매일복용함    매일복용중


================================================================================
[6] 종합 요약
================================================================================
  완전 정합 (Sf=1.0):             0건 (0.0%)
  Surface Variation (Trivial):    6건 (0.6%)
  Numerical Distortion (Minor):  23건 (2.3%)
  Categorical Mutation (Major): 117건 (11.5%)
  Critical (심각/실패):         872건 (85.7%)

  실질적 무결성 (정합+Trivial): 6건 (0.6%)


저장 완료:
  - hallucination_error_detail.csv  (개별 오류 단위, 환각유형 + 오류원인 포함)
  - hallucination_record_summary.csv (레코드 단위 요약)